# frozen_string_literal: true

module AppleVerification
  module LiveValidation
    # Renders the Markdown acceptance report destined for docs/rdrs/. The
    # renderer is fail-closed by construction: a criterion is satisfied only
    # when at least one scenario exists for it and every recorded row for
    # that criterion passed on a live run.
    # @spec APPLE-LIVE-007
    class Report
      GROUP_SECTIONS = {
        functional: "Functional evidence",
        recovery: "Recovery evidence",
        isolation: "Isolation evidence",
        network_policy: "Network policy evidence",
        capacity: "Capacity evidence",
        reporting: "Reporting evidence"
      }.freeze

      def initialize(result:, archive_path:)
        @result = result
        @archive_path = archive_path
      end

      def render
        <<~MARKDOWN
          # RDR-068 Live Validation Report

          Generated by `bin/apple-verify-live` for issue #3978 (live-host
          acceptance validation of RDR-068). Evidence statuses are fail-closed:
          a criterion is satisfied only by live, passing scenario runs.

          ## Run metadata

          #{metadata_lines.map { |line| "- #{line}" }.join("\n")}

          ## Acceptance criteria

          | Criterion | Description | Status | Evidence |
          |---|---|---|---|
          #{criterion_rows.join("\n")}

          #{evidence_sections}

          ## Gaps

          #{gap_lines}

          ## Archival

          This report is archived at `#{@archive_path}` and must be
          cross-referenced from the next RDR-068 closeout. Regenerate it with
          `bin/apple-verify-live --run --out #{@archive_path}` on the macOS
          host; see `docs/rdrs/live-validation-runbook-rdr-068.md` for the
          operator procedure.
        MARKDOWN
      end

      private

      attr_reader :result, :archive_path

      def metadata_lines
        [
          "started: #{result.started_at.iso8601}",
          "finished: #{result.finished_at.iso8601}",
          "duration: #{((result.finished_at - result.started_at) / 60).round(1)} minutes",
          "repeats: #{result.repeats} (clean clones per functional scenario)",
          *result.environment.map { |key, value| "#{key}: #{value}" }
        ]
      end

      def criterion_rows
        Suite::CRITERIA.map { |criterion, description| criterion_row(criterion, description) }
      end

      # Fail-closed: a criterion is satisfied only when every scenario the
      # suite defines for it has at least one evidence row and every row
      # passed on a live run.
      def criterion_row(criterion, description)
        scenarios = Suite.for_criterion(criterion)
        rows = result.rows_for(scenarios.map(&:id))
        satisfied = scenarios.present? && scenarios.all? { |scenario| scenario_passed?(scenario) }
        "| #{criterion} | #{description} | #{satisfied ? 'satisfied' : 'unmet'} | #{criterion_evidence(scenarios, rows)} |"
      end

      def scenario_passed?(scenario)
        rows = result.evidence_for(scenario.id)
        rows.present? && rows.all?(&:passed?)
      end

      def criterion_evidence(scenarios, rows)
        return "0 scenarios executed" if rows.empty?

        missing = scenarios.count { |scenario| result.evidence_for(scenario.id).empty? }
        base = "#{rows.count(&:passed?)}/#{rows.size} scenarios passed"
        missing.zero? ? base : "#{base} (#{missing} not executed)"
      end

      def evidence_sections
        GROUP_SECTIONS.filter_map do |group, title|
          rows = result.rows_for(Suite.group(group).map(&:id))
          next if rows.empty?

          <<~SECTION
            ## #{title}

            | Scenario | Status | Detail | References |
            |---|---|---|---|
            #{rows.map { |row| evidence_row(row) }.join("\n")}
          SECTION
        end.join("\n")
      end

      def evidence_row(row)
        references = row.references.map { |reference| "#{reference['kind']}##{reference['id']}" }.join(", ")
        "| #{row.scenario_id} | #{row.status} | #{escape_inline(row.detail)} | #{references} |"
      end

      def gap_lines
        gaps = result.evidence.reject(&:passed?)
        return "No gaps: every executed scenario passed on this run." if gaps.empty?

        gaps.map { |row| "- **#{row.scenario_id}** (#{row.status}) — #{escape_inline(row.detail)}" }.join("\n")
      end

      # Detail text is entity-escaped rather than backslash-escaped: the
      # rendered cell keeps its literal characters, and no pipe or
      # backslash survives to act as (or mask) a table delimiter.
      def escape_inline(detail)
        detail.to_s.gsub("\\", "&#92;").tr("\r\n", " ").gsub("|", "&#124;")
      end
    end
  end
end
