// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import FormSubmitController from "./form_submit_controller"
application.register("form-submit", FormSubmitController)

import RepositorySelectorController from "./repository_selector_controller"
application.register("repository-selector", RepositorySelectorController)
