// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import FormSubmitController from "./form_submit_controller"
application.register("form-submit", FormSubmitController)

import RepositorySelectorController from "./repository_selector_controller"
application.register("repository-selector", RepositorySelectorController)

import MobileMenuController from "./mobile_menu_controller"
application.register("mobile-menu", MobileMenuController)

import GoalToggleController from "./goal_toggle_controller"
application.register("goal-toggle", GoalToggleController)

import SortableController from "./sortable_controller"
application.register("sortable", SortableController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import TestAgentController from "./test_agent_controller"
application.register("test-agent", TestAgentController)

import LocalTimeController from "./local_time_controller"
application.register("local-time", LocalTimeController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import LiveDashboardController from "./live_dashboard_controller"
application.register("live-dashboard", LiveDashboardController)

import ElapsedTimeController from "./elapsed_time_controller"
application.register("elapsed-time", ElapsedTimeController)

import ProviderFormController from "./provider_form_controller"
application.register("provider-form", ProviderFormController)

import ConfirmDeleteController from "./confirm_delete_controller"
application.register("confirm-delete", ConfirmDeleteController)
