global:
  resolve_timeout: 5m

route:
  receiver: "null"
  group_by: ["alertname", "severity", "service"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  routes:
    - receiver: "null"
      matchers:
        - severity="critical"
    - receiver: "null"
      matchers:
        - severity="warning"

receivers:
  - name: "null"

inhibit_rules:
  - source_matchers:
      - severity="critical"
    target_matchers:
      - severity="warning"
    equal: ["alertname", "service"]
