#!/bin/bash
# No-op pg_dump - we don't need to dump schema in CI
# Just create an empty output file if --file is specified
while [[ $# -gt 0 ]]; do
  case "$1" in
    --file)
      shift
      # Don't overwrite existing structure.sql
      ;;
    *)
      ;;
  esac
  shift 2>/dev/null
done
exit 0
