#!/usr/bin/env ruby
# frozen_string_literal: true

require "pg"
require "uri"

args = ARGV.dup
file = nil
dbname = nil

until args.empty?
  arg = args.shift

  case arg
  when "--file"
    file = args.shift
  when /\A--file=(.+)\z/
    file = Regexp.last_match(1)
  when "--dbname"
    dbname = args.shift
  when /\A--dbname=(.+)\z/
    dbname = Regexp.last_match(1)
  when /\A-/
    next
  else
    dbname ||= arg
  end
end

abort "psql shim requires --file" unless file

database_url = ENV.fetch("DATABASE_URL")
uri = URI.parse(database_url)

dbname ||= uri.path.delete_prefix("/")
abort "psql shim could not determine database name" if dbname.nil? || dbname.empty?

connection = PG.connect(
  host: uri.host,
  port: uri.port,
  dbname: dbname,
  user: uri.user,
  password: uri.password
)

sql = File.read(file)
statements = []
buffer = +""
single_quote = false
double_quote = false
line_comment = false
block_comment = false
dollar_tag = nil
i = 0

while i < sql.length
  char = sql[i]
  pair = sql[i, 2]

  if line_comment
    buffer << char
    line_comment = false if char == "\n"
    i += 1
    next
  end

  if block_comment
    buffer << char
    if pair == "*/"
      buffer << sql[i + 1]
      block_comment = false
      i += 2
    else
      i += 1
    end
    next
  end

  if dollar_tag
    if sql[i, dollar_tag.length] == dollar_tag
      buffer << dollar_tag
      i += dollar_tag.length
      dollar_tag = nil
    else
      buffer << char
      i += 1
    end
    next
  end

  if single_quote
    buffer << char
    if char == "'" && sql[i - 1] != "\\"
      if sql[i + 1] == "'"
        buffer << "'"
        i += 2
      else
        single_quote = false
        i += 1
      end
    else
      i += 1
    end
    next
  end

  if double_quote
    buffer << char
    if char == '"' && sql[i - 1] != "\\"
      if sql[i + 1] == '"'
        buffer << '"'
        i += 2
      else
        double_quote = false
        i += 1
      end
    else
      i += 1
    end
    next
  end

  if pair == "--"
    buffer << pair
    line_comment = true
    i += 2
    next
  end

  if pair == "/*"
    buffer << pair
    block_comment = true
    i += 2
    next
  end

  if char == "'"
    buffer << char
    single_quote = true
    i += 1
    next
  end

  if char == '"'
    buffer << char
    double_quote = true
    i += 1
    next
  end

  if char == "$"
    closing = sql.index("$", i + 1)
    if closing
      tag = sql[i..closing]
      if tag.match?(/\A\$[A-Za-z0-9_]*\$\z/)
        buffer << tag
        dollar_tag = tag
        i = closing + 1
        next
      end
    end
  end

  if char == ";"
    statement = buffer.strip
    statements << statement unless statement.empty?
    buffer.clear
    i += 1
    next
  end

  buffer << char
  i += 1
end

statement = buffer.strip
statements << statement unless statement.empty?

connection.exec("BEGIN")
begin
  statements.each do |statement_text|
    connection.exec(statement_text)
  end
  connection.exec("COMMIT")
rescue StandardError
  connection.exec("ROLLBACK")
  raise
ensure
  connection.close
end
