# frozen_string_literal: true

require "rails_helper"

RSpec.describe Llm::GenerateIssueTitle do
  let(:summary) { "The authentication system uses JWT tokens with a 24-hour expiry." }
  let(:api_key) { "sk-ant-test-key" }

  before do
    allow(Rails.application.credentials).to receive(:dig).and_call_original
    allow(Rails.application.credentials).to receive(:dig).with(:llm, :anthropic_api_key).and_return(nil)
    allow(ENV).to receive(:[]).and_call_original
    allow(ENV).to receive(:[]).with("ANTHROPIC_API_KEY").and_return(api_key)
    allow(ENV).to receive(:fetch).and_call_original
  end

  describe ".call" do
    it "returns a title generated by the Anthropic API" do
      stub_request(:post, Llm::GenerateIssueTitle::API_URL)
        .to_return(
          status: 200,
          headers: { "Content-Type" => "application/json" },
          body: {
            content: [ { type: "text", text: "JWT authentication system review" } ]
          }.to_json
        )

      title = described_class.call(summary: summary)

      expect(title).to eq("JWT authentication system review")
    end

    it "strips quotes from the generated title" do
      stub_request(:post, Llm::GenerateIssueTitle::API_URL)
        .to_return(
          status: 200,
          headers: { "Content-Type" => "application/json" },
          body: {
            content: [ { type: "text", text: '"JWT authentication system review"' } ]
          }.to_json
        )

      title = described_class.call(summary: summary)

      expect(title).to eq("JWT authentication system review")
    end

    it "truncates titles longer than MAX_TITLE_LENGTH" do
      long_title = "A" * 300
      stub_request(:post, Llm::GenerateIssueTitle::API_URL)
        .to_return(
          status: 200,
          headers: { "Content-Type" => "application/json" },
          body: {
            content: [ { type: "text", text: long_title } ]
          }.to_json
        )

      title = described_class.call(summary: summary)

      expect(title.length).to be <= Llm::GenerateIssueTitle::MAX_TITLE_LENGTH
    end

    it "returns nil for blank summary" do
      expect(described_class.call(summary: "")).to be_nil
      expect(described_class.call(summary: nil)).to be_nil
    end

    it "returns nil when no API key is configured" do
      allow(Rails.application.credentials).to receive(:dig).with(:llm, :anthropic_api_key).and_return(nil)
      allow(ENV).to receive(:[]).with("ANTHROPIC_API_KEY").and_return(nil)

      title = described_class.call(summary: summary)

      expect(title).to be_nil
    end

    it "uses credentials API key when ENV is not set" do
      allow(Rails.application.credentials).to receive(:dig).with(:llm, :anthropic_api_key).and_return("sk-creds-key")
      allow(ENV).to receive(:[]).with("ANTHROPIC_API_KEY").and_return(nil)

      stub = stub_request(:post, Llm::GenerateIssueTitle::API_URL)
        .with(headers: { "x-api-key" => "sk-creds-key" })
        .to_return(
          status: 200,
          headers: { "Content-Type" => "application/json" },
          body: {
            content: [ { type: "text", text: "Test title" } ]
          }.to_json
        )

      described_class.call(summary: summary)

      expect(stub).to have_been_requested
    end

    it "returns nil on API error and logs warning" do
      stub_request(:post, Llm::GenerateIssueTitle::API_URL)
        .to_return(status: 500, body: "Internal Server Error")

      expect(Rails.logger).to receive(:warn).with(hash_including(
        message: "llm.generate_issue_title_failed"
      ))

      title = described_class.call(summary: summary)

      expect(title).to be_nil
    end

    it "returns nil on timeout and logs warning" do
      stub_request(:post, Llm::GenerateIssueTitle::API_URL).to_timeout

      expect(Rails.logger).to receive(:warn).with(hash_including(
        message: "llm.generate_issue_title_failed"
      ))

      title = described_class.call(summary: summary)

      expect(title).to be_nil
    end

    it "sends the correct request to Anthropic API" do
      stub = stub_request(:post, Llm::GenerateIssueTitle::API_URL)
        .with(
          headers: {
            "x-api-key" => api_key,
            "anthropic-version" => "2023-06-01"
          }
        )
        .to_return(
          status: 200,
          headers: { "Content-Type" => "application/json" },
          body: {
            content: [ { type: "text", text: "Test title" } ]
          }.to_json
        )

      described_class.call(summary: summary)

      expect(stub).to have_been_requested
    end

    it "truncates long summaries in the request" do
      long_summary = "x" * 10_000

      stub = stub_request(:post, Llm::GenerateIssueTitle::API_URL)
        .with { |req|
          body = JSON.parse(req.body)
          user_content = body["messages"][0]["content"]
          user_content.length <= Llm::GenerateIssueTitle::MAX_SUMMARY_INPUT + 200
        }
        .to_return(
          status: 200,
          headers: { "Content-Type" => "application/json" },
          body: {
            content: [ { type: "text", text: "Test title" } ]
          }.to_json
        )

      described_class.call(summary: long_summary)

      expect(stub).to have_been_requested
    end
  end
end
