# frozen_string_literal: true

require "rails_helper"

RSpec.describe Activities::CreatePullRequestActivity do
  let(:activity) { described_class.new }
  let(:project) { create(:project) }
  let(:issue) { create(:issue, project: project) }
  let(:agent_run) { create(:agent_run, :with_git_context, :with_metrics, project: project, issue: issue) }
  let(:github_client) { instance_double(GithubClient) }
  let(:pr_response) { Struct.new(:html_url, :number).new("https://github.com/owner/repo/pull/42", 42) }

  before do
    allow(GithubClient).to receive(:new).and_return(github_client)
    allow(github_client).to receive(:create_pull_request).and_return(pr_response)
    allow(github_client).to receive(:add_labels_to_issue)
    # Stub external agent harness so Llm::GeneratePrDescription runs without real external calls.
    # By default, return a failed response so the activity falls back to raw summary.
    allow(AgentHarness).to receive(:send_message)
      .and_return(instance_double(AgentHarness::Response, success?: false, output: ""))
  end

  describe "#execute" do
    it "creates a pull request via the GitHub API" do
      expect(github_client).to receive(:create_pull_request).with(
        project.full_name,
        base: project.default_branch,
        head: agent_run.branch_name,
        title: "Fix ##{issue.github_number}: #{issue.title}",
        body: a_string_including("Closes ##{issue.github_number}"),
        draft: true
      ).and_return(pr_response)

      result = activity.execute(agent_run_id: agent_run.id)

      expect(result[:pull_request_url]).to eq("https://github.com/owner/repo/pull/42")
      expect(result[:pull_request_number]).to eq(42)
    end

    it "marks the agent run as completed with PR details" do
      activity.execute(agent_run_id: agent_run.id)

      agent_run.reload
      expect(agent_run.status).to eq("completed")
      expect(agent_run.pull_request_url).to eq("https://github.com/owner/repo/pull/42")
      expect(agent_run.pull_request_number).to eq(42)
    end

    it "adds the generated and automation labels to the PR" do
      expect(github_client).to receive(:add_labels_to_issue).with(
        project.full_name, 42, [ "paid-generated", "paid-automation" ]
      )

      activity.execute(agent_run_id: agent_run.id)
    end

    it "logs the PR creation to agent run" do
      activity.execute(agent_run_id: agent_run.id)

      log = agent_run.agent_run_logs.last
      expect(log.log_type).to eq("system")
      expect(log.content).to include("https://github.com/owner/repo/pull/42")
    end

    it "includes agent stdout in the PR body when available" do
      agent_run.log!("stdout", "Here are the changes I made to fix the issue.")

      expect(github_client).to receive(:create_pull_request).with(
        anything,
        hash_including(
          body: a_string_including("Here are the changes I made")
            .and(including("Closes ##{issue.github_number}"))
        )
      ).and_return(pr_response)

      activity.execute(agent_run_id: agent_run.id)
    end

    it "uses fallback summary when no stdout is available" do
      expect(github_client).to receive(:create_pull_request).with(
        anything,
        hash_including(
          body: a_string_including("automatically generated by")
            .and(including("Closes ##{issue.github_number}"))
        )
      ).and_return(pr_response)

      activity.execute(agent_run_id: agent_run.id)
    end

    it "handles missing issue gracefully" do
      agent_run_no_issue = create(:agent_run, :with_custom_prompt, :with_git_context, project: project)

      expect(github_client).to receive(:create_pull_request).with(
        anything,
        hash_including(title: "Agent changes")
      ).and_return(pr_response)

      result = activity.execute(agent_run_id: agent_run_no_issue.id)
      expect(result[:pull_request_url]).to eq("https://github.com/owner/repo/pull/42")
    end

    it "does not fail when label addition fails" do
      allow(github_client).to receive(:add_labels_to_issue)
        .and_raise(GithubClient::ApiError.new("Label not found"))

      expect {
        activity.execute(agent_run_id: agent_run.id)
      }.not_to raise_error
    end

    context "when auto_add_labels_enabled is false" do
      before { project.update!(auto_add_labels_enabled: false) }

      it "does not add labels to the PR" do
        activity.execute(agent_run_id: agent_run.id)

        expect(github_client).not_to have_received(:add_labels_to_issue)
      end
    end

    context "when auto_add_labels_enabled is true with custom labels" do
      before do
        project.update!(
          auto_add_labels_enabled: true,
          generated_label_name: "custom-generated",
          automation_label_name: "custom-automation"
        )
      end

      it "adds both custom labels to the PR" do
        activity.execute(agent_run_id: agent_run.id)

        expect(github_client).to have_received(:add_labels_to_issue).with(
          project.full_name, 42, [ "custom-generated", "custom-automation" ]
        )
      end
    end

    context "when LLM generates a structured description" do
      let(:llm_description) { "## Summary\n\nAdds OAuth support for third-party integrations." }

      it "uses the LLM-generated description in the PR body" do
        agent_run.log!("stdout", "Added OAuth middleware")
        allow(AgentHarness).to receive(:send_message)
          .and_return(instance_double(AgentHarness::Response, success?: true, output: llm_description))

        expect(github_client).to receive(:create_pull_request).with(
          anything,
          hash_including(
            body: a_string_including("## Summary")
              .and(including("OAuth support"))
              .and(including("Closes ##{issue.github_number}"))
          )
        ).and_return(pr_response)

        activity.execute(agent_run_id: agent_run.id)
      end

      it "passes issue context to the LLM service via AgentHarness" do
        agent_run.log!("stdout", "Added OAuth middleware")
        allow(AgentHarness).to receive(:send_message)
          .and_return(instance_double(AgentHarness::Response, success?: true, output: llm_description))

        activity.execute(agent_run_id: agent_run.id)

        expect(AgentHarness).to have_received(:send_message).with(
          a_string_including(issue.title).and(including(issue.body)),
          provider: :claude,
          model: Llm::GeneratePrDescription::DEFAULT_MODEL,
          timeout: Llm::GeneratePrDescription::TIMEOUT
        )
      end

      it "falls back to raw summary when LLM provider fails and logs with context" do
        agent_run.log!("stdout", "Raw agent output here")
        allow(AgentHarness).to receive(:send_message)
          .and_raise(AgentHarness::ProviderError.new("Provider unavailable"))
        mock_logger = instance_double(ActiveSupport::Logger, info: nil)
        allow(activity).to receive(:logger).and_return(mock_logger)
        expect(mock_logger).to receive(:warn).with(hash_including(
          message: "agent_execution.pr_description_failed",
          agent_run_id: agent_run.id,
          issue_number: issue.github_number,
          error_class: "AgentHarness::ProviderError"
        ))
        expect(github_client).to receive(:create_pull_request).with(
          anything,
          hash_including(body: a_string_including("Raw agent output here"))
        ).and_return(pr_response)

        activity.execute(agent_run_id: agent_run.id)
      end

      it "falls back to raw summary when LLM raises an unexpected error and logs with context" do
        agent_run.log!("stdout", "Raw agent output here")
        allow(AgentHarness).to receive(:send_message)
          .and_raise(RuntimeError.new("unexpected failure"))
        mock_logger = instance_double(ActiveSupport::Logger, info: nil)
        allow(activity).to receive(:logger).and_return(mock_logger)
        expect(mock_logger).to receive(:warn).with(hash_including(
          message: "agent_execution.pr_description_failed",
          agent_run_id: agent_run.id,
          issue_number: issue.github_number,
          error_class: "RuntimeError"
        ))
        expect(github_client).to receive(:create_pull_request).with(
          anything,
          hash_including(body: a_string_including("Raw agent output here"))
        ).and_return(pr_response)

        activity.execute(agent_run_id: agent_run.id)
      end

      it "falls back to raw summary when LLM returns a failed response" do
        agent_run.log!("stdout", "Raw agent output here")
        # Default before block already stubs a failed response

        expect(github_client).to receive(:create_pull_request).with(
          anything,
          hash_including(
            body: a_string_including("Raw agent output here")
          )
        ).and_return(pr_response)

        activity.execute(agent_run_id: agent_run.id)
      end
    end

    it "raises ActiveRecord::RecordNotFound for invalid agent_run_id" do
      expect {
        activity.execute(agent_run_id: -1)
      }.to raise_error(ActiveRecord::RecordNotFound)
    end
  end
end
