#!/bin/bash
DB=""
SQL_FILE=""
while [[ $# -gt 0 ]]; do
  case $1 in
    --file|-f) SQL_FILE="$2"; shift 2;;
    --set) shift 2;;
    --quiet|-q|--no-psqlrc) shift;;
    --output|-o) shift 2;;
    *) DB="$1"; shift;;
  esac
done
if [ -z "$SQL_FILE" ]; then
  exit 0
fi
BUNDLE_PATH=/workspace/vendor/bundle ruby -rpg -e "
conn = PG.connect(ENV['DATABASE_URL'])
conn.exec(File.read('$SQL_FILE'))
conn.close
"
