#!/usr/bin/env ruby
$LOAD_PATH.unshift '/workspace/vendor/bundle/ruby/3.4.0/gems/pg-1.6.3-aarch64-linux/lib'
require 'uri'
require 'pg'

file = nil
args = ARGV.dup
while arg = args.shift
  file = args.shift if arg == '--file'
end

if file && File.exist?(file)
  uri = URI.parse(ENV['DATABASE_URL'])
  conn = PG.connect(
    host: uri.host,
    port: uri.port,
    dbname: uri.path[1..],
    user: uri.user,
    password: uri.password
  )
  conn.exec("DROP SCHEMA public CASCADE; CREATE SCHEMA public;")
  sql = File.read(file)
  conn.exec(sql)
  conn.close
end
