# frozen_string_literal: true

class CreateContextIntakeQuestions < ActiveRecord::Migration[8.1]
  def change
    create_table :context_intake_questions,
      comment: "Catalog of data-driven business-context wizard questions, including authored and AI-generated follow-ups." do |t|
      t.references :project, null: true, foreign_key: true,
        comment: "Project-specific question ownership. Null means a shared default catalog question."
      t.string :key, null: false, limit: 200,
        comment: "Stable question key used to match answers and link follow-up relationships."
      t.text :question_text, null: false,
        comment: "Prompt text presented to the maintainer in the business-context wizard."
      t.string :section_key, null: false, limit: 100,
        comment: "Logical section identifier used for grouping and knowledge synthesis."
      t.string :section_title, null: false, limit: 200,
        comment: "Human-readable section heading shown in the wizard."
      t.string :category, null: false, limit: 100,
        comment: "Semantic category for reporting and future branching logic."
      t.integer :round, null: false, default: 1,
        comment: "Question round. Round 1 is the base questionnaire; later rounds are follow-ups."
      t.integer :section_order, null: false, default: 0,
        comment: "Section ordering within a round."
      t.integer :display_order, null: false, default: 0,
        comment: "Question ordering within its section and round."
      t.boolean :required, null: false, default: false,
        comment: "Whether the question must be answered before completing the session."
      t.boolean :is_follow_up, null: false, default: false,
        comment: "Marks questions that refine or extend prior answers."
      t.string :parent_question_key, limit: 200,
        comment: "Optional source question key this follow-up is refining."
      t.string :status, null: false, limit: 50, default: "approved",
        comment: "Review state for this question definition."
      t.string :provenance, null: false, limit: 50, default: "human",
        comment: "Whether the question was authored manually or generated by an agent."
      t.boolean :active, null: false, default: true,
        comment: "Whether this question is eligible to appear in the wizard."
      t.jsonb :conditions, null: false, default: {},
        comment: "Branching conditions that determine when the question should be shown."
      t.jsonb :validation_rules, null: false, default: {},
        comment: "Extensible validation metadata for future answer schemas."
      t.jsonb :metadata, null: false, default: {},
        comment: "Additional extensible metadata that should evolve without schema churn."
      t.timestamps
    end

    add_index :context_intake_questions, [ :project_id, :key ],
      unique: true,
      name: "idx_context_intake_questions_project_key"
    add_index :context_intake_questions, :key,
      unique: true,
      where: "project_id IS NULL",
      name: "idx_context_intake_questions_global_key_unique"
    add_index :context_intake_questions,
      [ :project_id, :active, :status ],
      name: "idx_context_intake_questions_visibility"
    add_index :context_intake_questions,
      [ :project_id, :parent_question_key ],
      name: "idx_context_intake_questions_parent"
    add_index :context_intake_questions,
      [ :project_id, :round, :section_order ],
      name: "idx_context_intake_questions_round_order"
  end
end
