# frozen_string_literal: true

module Knowledge
  module Collectors
    class SchemaCollector < BaseCollector
      SCHEMA_FILE = "db/schema.rb"

      # Tables generated by Rails internals, not application models.
      INTERNAL_TABLES = %w[
        ar_internal_metadata
        schema_migrations
        active_storage_blobs
        active_storage_attachments
        active_storage_variant_records
        action_text_rich_texts
        action_mailbox_inbound_emails
      ].freeze

      def collect
        skip!("#{SCHEMA_FILE} not found") unless repo_file_exists?(SCHEMA_FILE)

        content = read_repo_file(SCHEMA_FILE)
        tables = parse_schema(content)
        foreign_keys = parse_foreign_keys(content)

        tables.filter_map do |table|
          next if INTERNAL_TABLES.include?(table[:name])

          build_artifact(table, foreign_keys)
        end
      end

      def collector_type
        "schema"
      end

      private

      def parse_schema(content)
        tables = []
        current_table = nil

        content.each_line do |line|
          stripped = line.strip

          if (match = stripped.match(/\Acreate_table\s+"([^"]+)"/))
            current_table = { name: match[1], columns: [], indexes: [] }
            tables << current_table
          elsif current_table && stripped == "end"
            current_table = nil
          elsif current_table
            parse_column(stripped, current_table) ||
              parse_index(stripped, current_table)
          end
        end

        tables
      end

      def parse_column(line, table)
        match = line.match(/\At\.(\w+)\s+"([^"]+)"(.*)/)
        return false unless match

        type = match[1]
        name = match[2]
        options_str = match[3]

        return false if type == "index"

        column = { name: name, type: type }
        column[:null] = false if options_str.include?("null: false")
        if (default_match = options_str.match(/default:\s*("([^"]*)"|(\S+))/))
          column[:default] = default_match[2] || default_match[3]
        end

        table[:columns] << column
        true
      end

      def parse_index(line, table)
        match = line.match(/\At\.index\s+\[([^\]]+)\],\s*name:\s*"([^"]+)"(.*)/)
        return false unless match

        columns = match[1].scan(/"([^"]+)"/).flatten
        name = match[2]
        options_str = match[3]

        index = { columns: columns, name: name }
        index[:unique] = true if options_str.include?("unique: true")

        table[:indexes] << index
        true
      end

      def parse_foreign_keys(content)
        fks = []

        content.each_line do |line|
          stripped = line.strip
          match = stripped.match(/\Aadd_foreign_key\s+"([^"]+)",\s*"([^"]+)"(.*)/)
          next unless match

          from_table = match[1]
          to_table = match[2]
          options_str = match[3]

          fk = { from_table: from_table, to_table: to_table }
          if (col_match = options_str.match(/column:\s*"([^"]+)"/))
            fk[:column] = col_match[1]
          else
            fk[:column] = "#{to_table.singularize}_id"
          end

          fks << fk
        end

        fks
      end

      def build_artifact(table, all_foreign_keys)
        table_fks = all_foreign_keys.select { |fk| fk[:from_table] == table[:name] }
        associations = infer_associations(table, all_foreign_keys)

        definition_content = format_definition(table, table_fks)
        context_content = format_context(table, associations)

        {
          artifact_type: "schema",
          scope_path: "db/schema.rb",
          identifier: table[:name],
          content: definition_content,
          metadata: {
            table_name: table[:name],
            column_count: table[:columns].size,
            index_count: table[:indexes].size,
            foreign_key_count: table_fks.size,
            has_timestamps: table[:columns].any? { |c| c[:name] == "created_at" }
          },
          chunks: [
            {
              chunk_type: "definition",
              content: definition_content,
              scope_tags: [ "schema", table[:name] ],
              sequence: 0
            },
            {
              chunk_type: "context",
              content: context_content,
              scope_tags: [ "schema", "associations", table[:name] ],
              sequence: 1
            }
          ]
        }
      end

      def format_definition(table, table_fks)
        parts = [ "Table: #{table[:name]}" ]
        parts << "Columns: #{format_columns(table[:columns])}"
        parts << "Indexes: #{format_indexes(table[:indexes])}" if table[:indexes].any?
        parts << "Foreign Keys: #{format_foreign_keys(table_fks)}" if table_fks.any?
        parts.join("\n")
      end

      def format_columns(columns)
        columns.map { |c| format_column(c) }.join(", ")
      end

      def format_column(col)
        parts = [ "#{col[:name]} (#{col[:type]}" ]
        constraints = []
        constraints << "not null" if col[:null] == false
        constraints << "default: #{col[:default]}" if col[:default]
        parts << ", #{constraints.join(", ")}" if constraints.any?
        parts << ")"
        parts.join
      end

      def format_indexes(indexes)
        indexes.map do |idx|
          cols = idx[:columns].join(", ")
          unique_label = idx[:unique] ? " [unique]" : ""
          "#{idx[:name]} (#{cols}#{unique_label})"
        end.join("; ")
      end

      def format_foreign_keys(fks)
        fks.map { |fk| "#{fk[:column]} → #{fk[:to_table]}" }.join("; ")
      end

      def format_context(table, associations)
        parts = [ "Model: #{table[:name].classify}" ]
        parts << "Associations: #{associations.join(", ")}" if associations.any?

        polymorphic = detect_polymorphic(table)
        parts << "Polymorphic: #{polymorphic.join(", ")}" if polymorphic.any?

        parts.join("\n")
      end

      def infer_associations(table, all_foreign_keys)
        associations = []

        # belongs_to from foreign keys on this table
        table_fks = all_foreign_keys.select { |fk| fk[:from_table] == table[:name] }
        table_fks.each do |fk|
          model_name = fk[:column].delete_suffix("_id")
          associations << "belongs_to :#{model_name}"
        end

        # Also infer belongs_to from column naming when no explicit FK
        fk_columns = table_fks.map { |fk| fk[:column] }
        table[:columns].each do |col|
          next unless col[:name].end_with?("_id")
          next if fk_columns.include?(col[:name])

          model_name = col[:name].delete_suffix("_id")
          associations << "belongs_to :#{model_name} (inferred)"
        end

        # has_many from foreign keys referencing this table
        all_foreign_keys.each do |fk|
          next unless fk[:to_table] == table[:name]

          associations << "has_many :#{fk[:from_table]}"
        end

        associations
      end

      def detect_polymorphic(table)
        type_columns = table[:columns].select { |c| c[:name].end_with?("_type") }
        type_columns.filter_map do |tc|
          prefix = tc[:name].delete_suffix("_type")
          id_col = table[:columns].find { |c| c[:name] == "#{prefix}_id" }
          "#{prefix} (#{tc[:name]} + #{id_col[:name]})" if id_col
        end
      end
    end
  end
end
