# frozen_string_literal: true

module Knowledge
  module Collectors
    class SchemaCollector < BaseCollector
      STRUCTURE_SQL = "db/structure.sql"
      SCHEMA_RB = "db/schema.rb"

      # Tables generated by Rails internals, not application models.
      INTERNAL_TABLES = %w[
        ar_internal_metadata
        schema_migrations
        active_storage_blobs
        active_storage_attachments
        active_storage_variant_records
        action_text_rich_texts
        action_mailbox_inbound_emails
      ].freeze

      def collect
        schema_file = detect_schema_file
        content = read_repo_file(schema_file)

        tables, foreign_keys = if schema_file == STRUCTURE_SQL
          [ parse_sql_tables(content), parse_sql_foreign_keys(content) ]
        else
          [ parse_schema(content), parse_foreign_keys(content) ]
        end

        tables.filter_map do |table|
          next if INTERNAL_TABLES.include?(table[:name])
          next unless model_backed?(table[:name])

          build_artifact(table, foreign_keys, schema_file)
        end
      end

      def collector_type
        "schema"
      end

      private

      def detect_schema_file
        return SCHEMA_RB if repo_file_exists?(SCHEMA_RB)
        return STRUCTURE_SQL if repo_file_exists?(STRUCTURE_SQL)

        skip!("neither #{SCHEMA_RB} nor #{STRUCTURE_SQL} found")
      end

      # --- SQL (structure.sql) parsing ---

      def parse_sql_tables(content)
        tables = []
        current_table = nil

        content.each_line do |line|
          stripped = line.strip

          if (match = stripped.match(/\ACREATE TABLE\s+\S+\.(\S+)\s*\(/))
            current_table = { name: match[1], columns: [], indexes: [] }
            tables << current_table
          elsif current_table && stripped == ");"
            current_table = nil
          elsif current_table
            parse_sql_column(stripped, current_table)
          end
        end

        merge_sql_indexes(content, tables)
        tables
      end

      def parse_sql_column(line, table)
        # Skip id column, constraints, and blank lines
        return if line.start_with?("CONSTRAINT")
        return if line.blank?

        # Match: column_name type_with_optional_parens [NOT NULL] [DEFAULT ...]
        # Column names may be quoted (e.g., "position") for reserved words.
        match = line.match(/\A"?(\w+)"?\s+(.+)/)
        return unless match

        name = match[1]
        rest = match[2].sub(/,\z/, "").strip

        # Skip the id column auto-detected as primary key
        return if name == "id"

        type = map_sql_type(rest) || extract_raw_sql_type(rest)

        column = { name: name, type: type }
        column[:null] = false if rest.match?(/\bNOT NULL\b/)
        if (default_match = rest.match(/DEFAULT\s+('(?:[^']*)'|[^\s,]+)/i))
          raw = default_match[1].sub(/::\S+\z/, "")
          column[:default] = raw unless raw == "NULL"
        end

        table[:columns] << column
      end

      SQL_TYPE_MAP = {
        "bigint" => "bigint",
        "integer" => "integer",
        "smallint" => "integer",
        "boolean" => "boolean",
        "text" => "text",
        "json" => "json",
        "jsonb" => "jsonb",
        "uuid" => "uuid",
        "inet" => "inet",
        "date" => "date",
        "bytea" => "binary",
        "double precision" => "float",
        "real" => "float"
      }.freeze

      def map_sql_type(rest)
        # character varying / varchar -> string
        return "string" if rest.match?(/\Acharacter varying\b/i)
        # numeric/decimal
        return "decimal" if rest.match?(/\Anumeric\b/i)
        # timestamp variants
        return "datetime" if rest.match?(/\Atimestamp\b/i)

        base_type = rest.split(/[\s(]/, 2).first&.downcase
        SQL_TYPE_MAP[base_type]
      end

      def extract_raw_sql_type(rest)
        rest.split(/\s+(?:NOT NULL|DEFAULT)\b|,/i, 2).first.strip.downcase
      end

      def merge_sql_indexes(content, tables)
        table_lookup = tables.index_by { |t| t[:name] }

        content.each_line do |line|
          stripped = line.strip
          match = stripped.match(
            /\ACREATE\s+(UNIQUE\s+)?INDEX\s+(\S+)\s+ON\s+\S+\.(\S+)\s+USING\s+\S+\s+\(([^)]+)\)/
          )
          next unless match

          unique = match[1].present?
          index_name = match[2]
          table_name = match[3]
          columns = match[4].split(",").filter_map { |part| extract_index_column(part) }

          table = table_lookup[table_name]
          next unless table

          index = { columns: columns, name: index_name }
          index[:unique] = true if unique

          table[:indexes] << index
        end
      end

      def parse_sql_foreign_keys(content)
        fks = []
        current_alter_table = nil
        content.each_line do |line|
          stripped = line.strip

          if (alter_match = stripped.match(/\AALTER TABLE ONLY\s+\S+\.(\S+)/))
            current_alter_table = alter_match[1]
          elsif current_alter_table
            fk_match = stripped.match(
              /ADD CONSTRAINT\s+\S+\s+FOREIGN KEY\s+\((\w+)\)\s+REFERENCES\s+\S+\.(\w+)\(/
            )
            if fk_match
              fks << {
                from_table: current_alter_table,
                to_table: fk_match[2],
                column: fk_match[1]
              }
            end
            # Reset alter table context on blank line or next ALTER TABLE
            current_alter_table = nil if stripped.blank?
          end
        end

        fks
      end

      def extract_index_column(part)
        token = part.strip.split(/\s+/, 2).first.to_s.delete_prefix("(").delete_suffix(")")
        token = token.split(".").last
        token = token.delete_prefix('"').delete_suffix('"')

        token if token.match?(/\A[a-zA-Z_]\w*\z/)
      end

      # --- Ruby (schema.rb) parsing ---

      def parse_schema(content)
        tables = []
        current_table = nil

        content.each_line do |line|
          stripped = line.strip

          if (match = stripped.match(/\Acreate_table\s+"([^"]+)"/))
            current_table = { name: match[1], columns: [], indexes: [] }
            tables << current_table
          elsif current_table && stripped == "end"
            current_table = nil
          elsif current_table
            parse_column(stripped, current_table) ||
              parse_index(stripped, current_table)
          end
        end

        tables
      end

      def parse_column(line, table)
        match = line.match(/\At\.(\w+)\s+"([^"]+)"(.*)/)
        return false unless match

        type = match[1]
        name = match[2]
        options_str = match[3]

        return false if type == "index"

        column = { name: name, type: type }
        column[:null] = false if options_str.include?("null: false")
        if (default_match = options_str.match(/default:\s*("([^"]*)"|([^,\s}]+))/))
          column[:default] = default_match[2] || default_match[3]
        end

        table[:columns] << column
        true
      end

      def parse_index(line, table)
        match = line.match(/\At\.index\s+\[([^\]]+)\],\s*name:\s*"([^"]+)"(.*)/)
        return false unless match

        columns = match[1].scan(/"([^"]+)"/).flatten
        name = match[2]
        options_str = match[3]

        index = { columns: columns, name: name }
        index[:unique] = true if options_str.include?("unique: true")

        table[:indexes] << index
        true
      end

      def parse_foreign_keys(content)
        fks = []

        content.each_line do |line|
          stripped = line.strip
          match = stripped.match(/\Aadd_foreign_key\s+"([^"]+)",\s*"([^"]+)"(.*)/)
          next unless match

          from_table = match[1]
          to_table = match[2]
          options_str = match[3]

          fk = { from_table: from_table, to_table: to_table }
          if (col_match = options_str.match(/column:\s*"([^"]+)"/))
            fk[:column] = col_match[1]
          else
            fk[:column] = "#{to_table.singularize}_id"
          end

          fks << fk
        end

        fks
      end

      # --- Shared formatting ---

      def build_artifact(table, all_foreign_keys, schema_file)
        table_fks = all_foreign_keys.select { |fk| fk[:from_table] == table[:name] }
        associations = infer_associations(table, all_foreign_keys)

        definition_content = format_definition(table, table_fks)
        context_content = format_context(table, associations)

        {
          artifact_type: "schema",
          scope_path: schema_file,
          identifier: table[:name],
          content: definition_content,
          metadata: {
            table_name: table[:name],
            column_count: table[:columns].size,
            index_count: table[:indexes].size,
            foreign_key_count: table_fks.size,
            has_timestamps: table[:columns].any? { |c| c[:name] == "created_at" }
          },
          chunks: [
            {
              chunk_type: "definition",
              content: definition_content,
              scope_tags: [ "schema", table[:name] ],
              sequence: 0
            },
            {
              chunk_type: "context",
              content: context_content,
              scope_tags: [ "schema", "associations", table[:name] ],
              sequence: 1
            }
          ]
        }
      end

      def format_definition(table, table_fks)
        parts = [ "Table: #{table[:name]}" ]
        parts << "Columns: #{format_columns(table[:columns])}"
        parts << "Indexes: #{format_indexes(table[:indexes])}" if table[:indexes].any?
        parts << "Foreign Keys: #{format_foreign_keys(table_fks)}" if table_fks.any?
        parts.join("\n")
      end

      def format_columns(columns)
        columns.map { |c| format_column(c) }.join(", ")
      end

      def format_column(col)
        parts = [ "#{col[:name]} (#{col[:type]}" ]
        constraints = []
        constraints << "not null" if col[:null] == false
        constraints << "default: #{col[:default]}" if col[:default]
        parts << ", #{constraints.join(", ")}" if constraints.any?
        parts << ")"
        parts.join
      end

      def format_indexes(indexes)
        indexes.map do |idx|
          cols = idx[:columns].join(", ")
          unique_label = idx[:unique] ? " [unique]" : ""
          "#{idx[:name]} (#{cols}#{unique_label})"
        end.join("; ")
      end

      def format_foreign_keys(fks)
        fks.map { |fk| "#{fk[:column]} → #{fk[:to_table]}" }.join("; ")
      end

      def format_context(table, associations)
        parts = [ "Model: #{table[:name].classify}" ]
        parts << "Associations: #{associations.join(", ")}" if associations.any?

        polymorphic = detect_polymorphic(table)
        parts << "Polymorphic: #{polymorphic.join(", ")}" if polymorphic.any?

        parts.join("\n")
      end

      def infer_associations(table, all_foreign_keys)
        associations = []

        # belongs_to from foreign keys on this table
        table_fks = all_foreign_keys.select { |fk| fk[:from_table] == table[:name] }
        table_fks.each do |fk|
          model_name = fk[:column].delete_suffix("_id")
          associations << "belongs_to :#{model_name}"
        end

        # Also infer belongs_to from column naming when no explicit FK
        fk_columns = table_fks.map { |fk| fk[:column] }
        table[:columns].each do |col|
          next unless col[:name].end_with?("_id")
          next if fk_columns.include?(col[:name])

          model_name = col[:name].delete_suffix("_id")
          associations << "belongs_to :#{model_name} (inferred)"
        end

        # has_many from foreign keys referencing this table
        all_foreign_keys.each do |fk|
          next unless fk[:to_table] == table[:name]

          associations << "has_many :#{fk[:from_table]}"
        end

        associations
      end

      # Checks whether the table has a corresponding model file in the repo.
      # Converts table name to the expected model path (e.g. "agent_runs" ->
      # "app/models/agent_run.rb") and verifies the file exists.
      def model_backed?(table_name)
        model_path = "app/models/#{table_name.singularize}.rb"
        repo_file_exists?(model_path)
      end

      def detect_polymorphic(table)
        type_columns = table[:columns].select { |c| c[:name].end_with?("_type") }
        type_columns.filter_map do |tc|
          prefix = tc[:name].delete_suffix("_type")
          id_col = table[:columns].find { |c| c[:name] == "#{prefix}_id" }
          "#{prefix} (#{tc[:name]} + #{id_col[:name]})" if id_col
        end
      end
    end
  end
end
