# frozen_string_literal: true

class Project < ApplicationRecord
  MERGE_METHODS = %w[squash merge rebase].freeze
  KNOWLEDGE_STATUSES = %w[pending collecting ready failed stale].freeze
  # "none" is not a method — it is represented by enabled: false at the top level
  REVIEW_METHODS = %w[copilot paid_agent codex ci_action manual].freeze

  PRIORITY_TIERS = %w[P1 P2 P3].freeze
  DEFAULT_PRIORITY_LABELS = { "P1" => "P1", "P2" => "P2", "P3" => "P3" }.freeze

  DEFAULT_REVIEW_SETTINGS = {
    "enabled" => false,
    "wait_for_reviews" => true,
    "methods" => {
      "copilot" => {
        "enabled" => false,
        "termination" => {
          "max_review_rounds" => 2,
          "stop_when_no_comments" => true,
          "quality_threshold" => nil,
          "timeout_minutes" => nil
        }
      },
      "paid_agent" => {
        "enabled" => false,
        "termination" => {
          "max_review_rounds" => 3,
          "stop_when_no_comments" => true,
          "quality_threshold" => nil,
          "timeout_minutes" => 30
        }
      },
      "codex" => {
        "enabled" => false,
        "termination" => {
          "max_review_rounds" => 2,
          "stop_when_no_comments" => true,
          "quality_threshold" => nil,
          "timeout_minutes" => 60
        }
      },
      "ci_action" => {
        "enabled" => false,
        "action_name" => nil,
        "termination" => {
          "max_review_rounds" => nil,
          "stop_when_no_comments" => true,
          "quality_threshold" => nil,
          "timeout_minutes" => nil
        }
      },
      "manual" => {
        "enabled" => false,
        "termination" => {
          "max_review_rounds" => nil,
          "stop_when_no_comments" => false,
          "quality_threshold" => nil,
          "timeout_minutes" => 1440
        }
      }
    }
  }.freeze

  AUTOMATION_SETTINGS = [
    { label: "Auto-Add Labels", attribute: :auto_add_labels_enabled,
     description: "Automatically add the generated label to PRs and issues created by Paid." }.freeze,
    { label: "Automation on Label", attribute: :automation_on_label_enabled,
     description: "Automatically create agent runs when the automation label is detected on issues or PRs." }.freeze,
    { label: "Auto-Pick Issues", attribute: :auto_pick_enabled,
     description: "Automatically start working on unblocked issues when no agent runs are active." }.freeze,
    { label: "Auto-Merge", attribute: :auto_merge_enabled,
     description: "Automatically merge PRs generated by Paid that are in a paid-ready state, have no unresolved review comments, and pass all CI checks." }.freeze,
    { label: "Auto-Fix Merge Conflicts", attribute: :auto_fix_merge_conflicts,
     description: "Automatically start a PR follow-up run when a paid-ready PR develops merge conflicts against the base branch." }.freeze,
    { label: "Aggregate PRs", attribute: :pr_aggregation_enabled,
     description: "When a feature is decomposed into sub-tasks, aggregate all agent changes into a single PR instead of individual PRs per sub-task." }.freeze,
    { label: "Inherit Priority Labels", attribute: :inherit_priority_labels,
     description: "When Paid creates a PR for an issue, copy any user-defined priority labels (P1/P2/P3) from the issue onto the new PR." }.freeze
  ].freeze

  belongs_to :account
  belongs_to :github_token, counter_cache: true
  belongs_to :created_by, class_name: "User", optional: true

  has_many :project_memberships, dependent: :destroy
  has_many :members, through: :project_memberships, source: :user
  has_many :issues, dependent: :destroy
  has_many :agent_runs, dependent: :destroy
  has_many :worktrees, dependent: :destroy
  has_many :cost_budgets, dependent: :destroy
  has_many :project_baselines, dependent: :destroy
  has_many :agent_run_anomalies, dependent: :destroy
  has_many :token_usages, through: :agent_runs
  has_many :workflow_states, dependent: :destroy
  has_many :prompts, dependent: :destroy
  has_many :style_guides, dependent: :destroy
  has_many :project_versions, dependent: :destroy
  has_many :knowledge_artifacts, dependent: :destroy
  has_many :knowledge_chunks, through: :knowledge_artifacts
  has_many :project_service_containers, dependent: :destroy
  has_many :service_containers, through: :project_service_containers
  has_many :decision_records, dependent: :destroy
  has_many :project_mcp_servers, dependent: :destroy
  has_many :mcp_server_definitions, through: :project_mcp_servers
  has_many :pre_commit_requirements, dependent: :destroy

  encrypts :webhook_secret

  before_validation :normalize_agent_co_author_trailer
  before_validation :normalize_priority_labels
  after_update_commit :invalidate_relationship_parsing_on_trust_change

  validates :name, presence: true
  validates :owner, presence: true
  validates :repo, presence: true
  validates :github_id, presence: true, uniqueness: { scope: :account_id }
  validates :poll_interval_seconds, numericality: { greater_than_or_equal_to: 60 }
  validates :max_pr_followup_runs, numericality: { greater_than_or_equal_to: 0 }
  validates :merge_method, inclusion: { in: MERGE_METHODS }
  validates :max_draft_review_rounds, numericality: { greater_than_or_equal_to: 0 }
  validates :generated_label_name, presence: true
  validates :automation_label_name, presence: true
  validates :security_severity_threshold, inclusion: { in: Issue::SEVERITY_ORDER }
  validates :code_scanning_interval_hours, numericality: { greater_than_or_equal_to: 24 }
  validates :knowledge_status, inclusion: { in: KNOWLEDGE_STATUSES }
  validates :max_tokens_per_run,
    numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 2_147_483_647 },
    allow_nil: true
  validates :token_limit_warning_threshold,
    numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 100 }
  validates :max_execution_seconds, numericality: { only_integer: true, greater_than_or_equal_to: 60, less_than_or_equal_to: 86_400 }
  validate :allowed_github_usernames_not_empty
  validate :agent_co_author_trailer_is_single_line
  validate :owner_reviewer_login_is_trusted, if: -> { owner_reviewer_login.present? }
  validate :github_token_belongs_to_same_account, if: -> { github_token.present? }
  validate :github_token_is_active, if: -> { github_token.present? && github_token_id_changed? }
  validate :created_by_belongs_to_same_account, if: -> { created_by.present? }
  validate :review_settings_valid
  validate :priority_labels_valid

  scope :active, -> { where(active: true) }
  scope :inactive, -> { where(active: false) }

  def self.ransackable_attributes(auth_object = nil)
    %w[name last_agent_run_at last_github_activity_at created_at]
  end

  def self.ransackable_associations(auth_object = nil)
    %w[]
  end

  after_create_commit :start_github_polling
  after_create_commit :enqueue_knowledge_collection
  after_update_commit :toggle_github_polling, if: :saved_change_to_active?
  after_update_commit :trigger_auto_pick, if: :auto_pick_just_enabled?
  after_destroy_commit :stop_github_polling
  after_destroy_commit :cleanup_qdrant_collection

  def full_name
    "#{owner}/#{repo}"
  end

  def github_url
    "https://github.com/#{full_name}"
  end

  def activate!
    update!(active: true)
  end

  def deactivate!
    update!(active: false)
  end

  def label_for_stage(stage)
    label_mappings[stage.to_s]
  end

  def set_label_for_stage(stage, label)
    self.label_mappings = label_mappings.merge(stage.to_s => label)
  end

  # Returns the user-configured GitHub label name for a priority tier ("P1"/"P2"/"P3").
  def priority_label_for(tier)
    effective_priority_labels[tier.to_s]
  end

  def effective_priority_labels
    overrides = (priority_labels || {}).slice(*PRIORITY_TIERS)
      .reject { |_, v| v.nil? || (v.is_a?(String) && v.strip.empty?) }
    DEFAULT_PRIORITY_LABELS.merge(overrides)
  end

  # All configured priority label names, used by queue ordering and PR inheritance.
  def priority_label_names
    effective_priority_labels.values_at(*PRIORITY_TIERS).compact
  end

  def worktree_service
    @worktree_service ||= WorktreeService.new(self)
  end

  def create_worktree_for(agent_run)
    worktree_service.create_worktree(agent_run)
  end

  def remove_worktree_for(agent_run)
    worktree_service.remove_worktree(agent_run)
  end

  def push_branch_for(agent_run)
    worktree_service.push_branch(agent_run)
  end

  # Returns the set of PR numbers that have queued automatic agent runs,
  # used by both the controller and Turbo broadcasts to drive the "Bump Priority" UI.
  def pr_numbers_with_queued_auto_continue
    agent_runs
      .where(trigger_type: "automatic", status: "queued")
      .where.not(source_pull_request_number: nil)
      .distinct
      .pluck(:source_pull_request_number)
      .to_set
  end

  # Returns the set of PR numbers that have any unfinished (queued/pending/running/paused) agent run,
  # used to suppress "Quick Run" when a run is already in progress (unique index would reject it).
  def pr_numbers_with_active_runs
    agent_runs
      .where(status: AgentRun::UNFINISHED_STATUSES)
      .where.not(source_pull_request_number: nil)
      .distinct
      .pluck(:source_pull_request_number)
      .to_set
  end

  def has_running_database_container?
    service_containers.running.where("image LIKE ?", "%postgres%").exists?
  end

  # Returns the effective owner of this project for capacity/settings lookups.
  # Falls back to the account's fallback owner (first owner by ID, or
  # first user by ID) when the creating user has been deleted.
  # Uses Account#fallback_owner for deterministic, shared resolution.
  def effective_owner
    created_by || account.fallback_owner
  end

  # Returns the ProviderApiKey record used for OpenAI embeddings, or nil.
  def openai_provider_api_key_record
    @openai_provider_api_key_record ||=
      effective_owner
        &.provider_api_keys
        &.for_api_service_type("openai")
        &.order(created_at: :desc, id: :desc)
        &.first
  end

  # Resolves the project owner's OpenAI API key for embeddings and semantic search.
  # Returns nil when no user key exists (callers fall back to ENV["OPENAI_API_KEY"]).
  def openai_api_key
    openai_provider_api_key_record&.api_key
  end

  def openai_api_key_configured?
    effective_owner
      &.provider_api_keys
      &.for_api_service_type("openai")
      &.exists? || false
  end

  # Returns true when an OpenAI API key is available from any source
  # (user-configured or platform-level ENV). Use this to determine whether
  # embedding/semantic search capabilities are available without leaking
  # which source provides the key.
  def semantic_search_available?
    openai_api_key_configured? || ENV["OPENAI_API_KEY"].present?
  end

  def trusted_github_user?(login)
    return false if login.blank?

    allowed_github_usernames.any? { |allowed| allowed.downcase == login.downcase }
  end

  # Returns the effective token limit per agent run at the project/account level.
  # Resolution: project override → account default.
  # NOTE: For full resolution (including user settings and global default),
  # use AgentRun#effective_max_tokens_per_run instead.
  def project_level_max_tokens_per_run
    max_tokens_per_run || account.default_max_tokens_per_run
  end

  # Returns the absolute token count at which a warning should be emitted.
  def token_limit_warning_at
    (project_level_max_tokens_per_run * token_limit_warning_threshold / 100.0).floor
  end

  def increment_metrics!(cost_cents:, tokens_used:)
    with_lock do
      update!(
        total_cost_cents: total_cost_cents + cost_cents,
        total_tokens_used: total_tokens_used + tokens_used
      )
    end
  end

  def touch_last_agent_run_at(timestamp = Time.current)
    update_column(:last_agent_run_at, timestamp)
  end

  def touch_last_github_activity_at(timestamp = Time.current)
    update_column(:last_github_activity_at, timestamp)
  end

  def touch_last_polled_at(timestamp = Time.current)
    update_column(:last_polled_at, timestamp)
  end

  # Shared staleness window used by both the health-check job and the
  # automation health UI. A poll workflow is considered stale when it has not
  # completed a poll cycle within 3× the configured interval plus a buffer.
  STALENESS_BUFFER = 3.minutes

  def poll_staleness_window
    (3 * poll_interval_seconds).seconds + STALENESS_BUFFER
  end

  def poll_stale?
    return false unless last_polled_at

    last_polled_at < poll_staleness_window.ago
  end

  # Double-checks staleness after a reload to avoid false positives from
  # a race with a just-completed poll cycle. Used by both the automation
  # health UI and the PollWorkflowHealthCheckJob.
  def poll_stale_with_recheck?
    return false unless poll_stale?

    reload
    poll_stale?
  end

  def broadcast_stats_update
    broadcast_replace_to(
      self, :project_updates,
      target: ActionView::RecordIdentifier.dom_id(self, :stats),
      partial: "projects/stats",
      locals: { project: self }
    )
  end

  def broadcast_agent_runs_update
    runs = agent_runs.recent.includes(:issue).limit(10).to_a
    AgentRun.preload_source_pull_requests(runs)
    broadcast_replace_to(
      self, :project_updates,
      target: ActionView::RecordIdentifier.dom_id(self, :agent_runs),
      partial: "projects/agent_runs",
      locals: { project: self, recent_agent_runs: runs }
    )
  end

  def broadcast_agent_runs_list_update
    runs = agent_runs.recent.includes(:issue).limit(50).to_a
    AgentRun.preload_source_pull_requests(runs)
    broadcast_replace_to(
      self, :agent_runs_list,
      target: ActionView::RecordIdentifier.dom_id(self, :agent_runs_list),
      partial: "agent_runs/table",
      locals: { project: self, agent_runs: runs }
    )
  end

  def broadcast_agent_run_detail_update(agent_run)
    final_provider_record = agent_run.final_provider_record
    attempted_providers = agent_run.attempted_providers_by_routing_key

    broadcast_replace_to(
      agent_run, :detail,
      target: ActionView::RecordIdentifier.dom_id(agent_run, :detail),
      partial: "agent_runs/detail",
      locals: {
        agent_run: agent_run,
        quality_metrics: agent_run.quality_metrics.with_composite_score.load,
        final_provider_record: final_provider_record,
        attempted_providers_by_routing_key: attempted_providers
      }
    )
  end

  def broadcast_issues_update
    open_items = issues.where(github_state: "open").order(github_number: :desc)
    displayed = open_items.issues_only.includes(:sub_issues).limit(25)
    lifecycle_statuses = Issue.lifecycle_statuses(displayed)
    broadcast_replace_to(
      self, :project_updates,
      target: ActionView::RecordIdentifier.dom_id(self, :issues),
      partial: "projects/issues",
      locals: { project: self, issues: displayed,
                issue_lifecycle_statuses: lifecycle_statuses }
    )
  end

  def broadcast_pull_requests_update
    open_items = issues.where(github_state: "open").order(github_number: :desc)
    broadcast_replace_to(
      self, :project_updates,
      target: ActionView::RecordIdentifier.dom_id(self, :pull_requests),
      partial: "projects/pull_requests",
      locals: {
        project: self,
        pull_requests: open_items.pull_requests_only.limit(25),
        pr_numbers_with_queued_auto_continue: pr_numbers_with_queued_auto_continue,
        pr_numbers_with_active_runs: pr_numbers_with_active_runs
      }
    )
  end

  def review_settings=(value)
    @effective_review_settings = nil
    super
  end

  def effective_review_settings
    return @effective_review_settings if defined?(@effective_review_settings) && @effective_review_settings

    rs = review_settings
    rs = rs.is_a?(Hash) ? rs : {}
    rs = rs.deep_stringify_keys if rs.respond_to?(:deep_stringify_keys)

    @effective_review_settings = DEFAULT_REVIEW_SETTINGS.deep_merge(rs)
  end

  def review_enabled?
    effective_review_settings["enabled"] == true
  end

  def wait_for_reviews?
    effective_review_settings["wait_for_reviews"] != false
  end

  def review_method_enabled?(method)
    effective_review_settings.dig("methods", method.to_s, "enabled") == true
  end

  def enabled_review_methods
    REVIEW_METHODS.select { |m| review_method_enabled?(m) }
  end

  # Returns the set of bot GitHub logins (downcased) for all enabled review
  # methods that have a known bot account (copilot, codex, etc.).
  def enabled_review_bot_logins
    ProviderSupport::PROVIDER_BOT_USERNAMES
      .slice(*enabled_review_methods)
      .values.flatten.map(&:downcase).to_set
  end

  def review_method_config(method)
    effective_review_settings.dig("methods", method.to_s) || {}
  end

  # Returns the GitHub login Paid should request to trigger a review-bot
  # review on a PR, or nil if no automated review method is enabled. Copilot
  # takes precedence when multiple bots are enabled; codex is used when
  # copilot is disabled because it does not auto-review draft PRs and
  # requires an explicit @-mention (see RequestReviewActivity).
  #
  # Returns nil when reviews are globally disabled via
  # review_settings["enabled"], even if an individual method sub-flag is
  # left enabled. Without this guard, RequestReviewActivity's nil-reviewers
  # fallback (driven by AgentExecutionWorkflow after every agent run)
  # would request bot reviews on projects that have opted out of review.
  def review_bot_request_login
    return nil unless review_enabled?
    return Activities::RequestReviewActivity::COPILOT_LOGIN if review_method_enabled?("copilot")
    return Activities::RequestReviewActivity::CODEX_LOGIN if review_method_enabled?("codex")

    nil
  end

  private

  def auto_pick_just_enabled?
    saved_change_to_auto_pick_enabled? && auto_pick_enabled?
  end

  def trigger_auto_pick
    ProcessRunQueueJob.perform_later
  rescue => e
    Rails.logger.error(message: "auto_pick.trigger_failed", project_id: id, error: e.message)
  end

  def enqueue_knowledge_collection
    EnqueueKnowledgeCollectionJob.perform_later(id)
  rescue => e
    Rails.logger.error(message: "knowledge.enqueue_collection_failed", project_id: id, error: e.message)
  end

  def start_github_polling
    return unless active?

    ProjectWorkflowManager.start_polling(self)
  rescue => e
    Rails.logger.error(message: "github_sync.start_polling_failed", project_id: id, error: e.message)
  end

  def stop_github_polling
    ProjectWorkflowManager.stop_polling(self)
  rescue => e
    Rails.logger.error(message: "github_sync.stop_polling_failed", project_id: id, error: e.message)
  end

  def cleanup_qdrant_collection
    QdrantCollectionCleanupJob.perform_later(id)
  end

  def toggle_github_polling
    if active?
      start_github_polling
    else
      stop_github_polling
    end
  end

  def github_token_belongs_to_same_account
    return if github_token.account_id == account_id

    errors.add(:github_token, "must belong to the same account")
  end

  def created_by_belongs_to_same_account
    return if created_by.account_id == account_id

    errors.add(:created_by, "must belong to the same account")
  end

  def github_token_is_active
    return if github_token.active?

    errors.add(:github_token, "must be active (not revoked or expired)")
  end

  def owner_reviewer_login_is_trusted
    return if trusted_github_user?(owner_reviewer_login)

    errors.add(:owner_reviewer_login, "must be in trusted GitHub usernames")
  end

  # Strip surrounding whitespace from each priority label value before
  # validation/persistence so a label entered as " critical " matches the
  # GitHub label "critical" instead of silently failing tier detection.
  def normalize_priority_labels
    return unless priority_labels.is_a?(Hash)

    self.priority_labels = priority_labels.each_with_object({}) do |(k, v), h|
      h[k] = v.is_a?(String) ? v.strip : v
    end
  end

  def priority_labels_valid
    return if priority_labels.nil? || priority_labels == {}

    unless priority_labels.is_a?(Hash)
      errors.add(:priority_labels, "must be a JSON object")
      return
    end

    PRIORITY_TIERS.each do |tier|
      value = priority_labels[tier]
      next if value.nil?
      unless value.is_a?(String) && value.strip.present?
        errors.add(:priority_labels, "#{tier} label must be a non-blank string")
      end
    end

    extras = priority_labels.keys - PRIORITY_TIERS
    if extras.any?
      errors.add(:priority_labels, "may only contain keys #{PRIORITY_TIERS.join(', ')} (got: #{extras.join(', ')})")
    end
  end

  def review_settings_valid
    return if review_settings.nil? || review_settings == {}

    unless review_settings.is_a?(Hash)
      errors.add(:review_settings, "must be a JSON object")
      return
    end

    # Normalize to string keys so validation works regardless of how the hash was constructed
    normalized = review_settings.deep_stringify_keys

    if normalized["enabled"] == true
      methods = normalized["methods"]
      unless methods.is_a?(Hash) && methods.any? { |_, c| c.is_a?(Hash) && c["enabled"] == true }
        errors.add(:review_settings, "must have at least one review method enabled when reviews are enabled")
      end
    end

    validate_review_methods_config(normalized)
  end

  def validate_review_methods_config(normalized)
    methods = normalized["methods"]
    return if methods.nil?

    unless methods.is_a?(Hash)
      errors.add(:review_settings, "methods must be a JSON object")
      return
    end

    methods.each do |method_name, config|
      unless REVIEW_METHODS.include?(method_name)
        errors.add(:review_settings, "contains unknown review method: #{method_name}")
        next
      end

      unless config.is_a?(Hash)
        errors.add(:review_settings, "#{method_name} config must be a JSON object")
        next
      end

      next unless config["enabled"] == true

      # ci_action requires an action_name so the system knows which GitHub Action to invoke
      if method_name == "ci_action" && config["action_name"].blank?
        errors.add(:review_settings, "ci_action requires a non-blank action_name when enabled")
      end

      termination = config["termination"]
      if termination.present? && !termination.is_a?(Hash)
        errors.add(:review_settings, "#{method_name} termination must be a JSON object")
        next
      end

      # Validate against the effective (defaults-merged) termination config so
      # missing termination falls back to the per-method defaults.
      effective_termination =
        termination ||
        DEFAULT_REVIEW_SETTINGS.dig("methods", method_name, "termination") ||
        {}
      validate_termination_config(method_name, effective_termination)
    end
  end

  def validate_termination_config(method_name, termination)
    return unless termination.is_a?(Hash)

    rounds = termination["max_review_rounds"]
    if rounds.present? && (!rounds.is_a?(Integer) || rounds < 1)
      errors.add(:review_settings, "#{method_name} max_review_rounds must be a positive integer")
    end

    timeout = termination["timeout_minutes"]
    if timeout.present? && (!timeout.is_a?(Integer) || timeout < 1)
      errors.add(:review_settings, "#{method_name} timeout_minutes must be a positive integer")
    end

    has_any_condition = termination["max_review_rounds"].present? ||
                        termination["stop_when_no_comments"] == true ||
                        termination["quality_threshold"].present? ||
                        termination["timeout_minutes"].present?
    return if has_any_condition

    errors.add(:review_settings, "#{method_name} must have at least one termination condition configured")
  end

  def normalize_agent_co_author_trailer
    stripped = agent_co_author_trailer.to_s.strip
    self.agent_co_author_trailer = stripped.present? ? stripped : nil
  end

  def agent_co_author_trailer_is_single_line
    return if agent_co_author_trailer.blank?
    return unless agent_co_author_trailer.match?(/[\r\n]/)

    errors.add(:agent_co_author_trailer, "must be a single line (no newlines)")
  end

  def allowed_github_usernames_not_empty
    return if allowed_github_usernames.is_a?(Array) && allowed_github_usernames.any?(&:present?)

    errors.add(:allowed_github_usernames, "must include at least one trusted GitHub username")
  end

  # When the trusted-user list changes, previously-parsed dependency and
  # parent/child relationships may reference content that is now untrusted
  # (or newly visible). Clear relationships_parsed_at so the next sync
  # re-parses every issue under the new trust policy.
  def invalidate_relationship_parsing_on_trust_change
    return unless saved_change_to_allowed_github_usernames?

    issues.update_all(relationships_parsed_at: nil)
  end
end
