#ifndef _WORKSPACE_BUNDLE_PR_908_RUBY_3_4_0_GEMS_NUMO_NARRAY_0_9_2_1_EXT_NUMO_NARRAY_NUMO_EXTCONF_H
#define _WORKSPACE_BUNDLE_PR_908_RUBY_3_4_0_GEMS_NUMO_NARRAY_0_9_2_1_EXT_NUMO_NARRAY_NUMO_EXTCONF_H
#define HAVE_STDBOOL_H 1
#define HAVE_STDINT_H 1
#define HAVE_TYPE_BOOL 1
#define HAVE_TYPE_U_INT8_T 1
#define HAVE_TYPE_U_INT16_T 1
#define HAVE_TYPE_INT32_T 1
#define HAVE_TYPE_U_INT32_T 1
#define HAVE_TYPE_INT64_T 1
#define HAVE_TYPE_U_INT64_T 1
#define HAVE_EXP10 1
#define HAVE_RB_ARITHMETIC_SEQUENCE_EXTRACT 1
#define HAVE_RB_CCOMPLEX 1
#endif
