# frozen_string_literal: true

module Screenshots
  # Builds and posts/updates a PR comment with inline screenshot images.
  #
  # Uses the `<!-- pr-screenshots-comment -->` marker for idempotent updates:
  # if a comment with that marker already exists, it is updated in place;
  # otherwise a new comment is created.
  #
  # @example
  #   Screenshots::PrComment.call(
  #     github_client: client,
  #     repo: "acme/web",
  #     pr_number: 42,
  #     commit_sha: "abc1234",
  #     screenshots: [
  #       { route_name: "dashboard", url: "https://signed-url..." },
  #       { route_name: "homepage",  url: "https://signed-url..." }
  #     ]
  #   )
  class PrComment
    MARKER = "<!-- pr-screenshots-comment -->"

    def self.call(...)
      new(...).call
    end

    # @param github_client [GithubClient] Authenticated GitHub API client
    # @param repo [String] Repository in "owner/name" format
    # @param pr_number [Integer] Pull request number
    # @param commit_sha [String] Commit SHA for the screenshots
    # @param screenshots [Array<Hash>] Each hash has :route_name and :url keys
    # @param artifact_name [String, nil] Workflow artifact name when screenshots
    #   were captured but inline storage is unavailable
    def initialize(github_client:, repo:, pr_number:, commit_sha:, screenshots:, artifact_name: nil)
      @github_client = github_client
      @repo = repo
      @pr_number = pr_number
      @commit_sha = commit_sha
      @screenshots = screenshots
      @artifact_name = artifact_name
    end

    # Posts or updates the PR comment with screenshot images.
    #
    # @return [Sawyer::Resource] The created or updated comment
    def call
      body = build_comment_body
      existing = find_existing_comment

      if existing
        @github_client.update_comment(@repo, existing.id, body)
      else
        @github_client.add_comment(@repo, @pr_number, body)
      end
    end

    # Builds the markdown comment body without posting it.
    #
    # @return [String]
    def build_comment_body
      if @screenshots.empty? && @artifact_name.present?
        return [
          MARKER,
          "## UI Screenshots",
          "",
          "This PR includes **UI-facing changes**, but inline screenshot upload is unavailable for commit `#{short_sha}`.",
          "",
          "Download the `#{@artifact_name}` workflow artifact from this run to review the captured PNG files.",
          "",
          "---",
          "_Generated by Paid_",
          ""
        ].join("\n")
      end

      if @screenshots.empty?
        return "#{MARKER}\n## UI Screenshots\n\nNo screenshots captured for commit `#{short_sha}`.\n"
      end

      lines = [ MARKER ]
      lines << "## UI Screenshots"
      lines << ""
      lines << "This PR includes **UI-facing changes**. Screenshots captured from commit `#{short_sha}`."
      lines << ""
      lines << "### Pages captured"
      lines << ""
      lines << "| Page | Screenshot |"
      lines << "|------|-----------|"

      @screenshots.sort_by { |s| s[:route_name] }.each do |screenshot|
        name = screenshot[:route_name]
        url = screenshot[:url]
        lines << "| #{humanize_route(name)} | ![#{name}](#{url}) |"
      end

      lines << ""
      lines << "---"
      lines << "_Generated by Paid_"
      lines << ""

      lines.join("\n")
    end

    private

    def short_sha
      @commit_sha[0, 7]
    end

    def humanize_route(route_name)
      route_name.to_s.tr("_", " ").gsub(/\b\w/, &:upcase)
    end

    def find_existing_comment
      comments = @github_client.issue_comments(@repo, @pr_number)
      comments.find { |c| c.body&.start_with?(MARKER) }
    end
  end
end
