# frozen_string_literal: true

module Screenshots
  # Builds and posts/updates a PR comment with inline screenshot images.
  #
  # Uses the `<!-- pr-screenshots-comment -->` marker for idempotent updates:
  # if a comment with that marker already exists, it is updated in place;
  # otherwise a new comment is created.
  #
  # When a screenshot includes an animated `:gif_url` (produced from multi-frame
  # capture input), the GIF is rendered inline instead of the static PNG.
  # The static PNG remains the fallback for screenshot-only captures,
  # preserving the existing before/after comparison UX.
  #
  # @example
  #   Screenshots::PrComment.call(
  #     github_client: client,
  #     repo: "acme/web",
  #     pr_number: 42,
  #     commit_sha: "abc1234",
  #     screenshots: [
  #       { route_name: "dashboard", url: "https://signed-url...", gif_url: "https://gif-url..." },
  #       { route_name: "homepage",  url: "https://signed-url..." }
  #     ]
  #   )
  class PrComment
    MARKER = "<!-- pr-screenshots-comment -->"

    def self.call(...)
      new(...).call
    end

    # @param github_client [GithubClient] Authenticated GitHub API client
    # @param repo [String] Repository in "owner/name" format
    # @param pr_number [Integer] Pull request number
    # @param commit_sha [String] Commit SHA for the screenshots
    # @param screenshots [Array<Hash>] Each hash has :route_name, :url, and
    #   optional :gif_url, :video_url, :summary, and :video_filename keys
    # @param previous_screenshots [Hash<String, String>] Mapping of route_name to
    #   signed URL from the previous commit's capture, used for before/after comparison
    # @param artifact_name [String, nil] Workflow artifact name when screenshots
    #   were captured but inline storage is unavailable
    # @param status [String] Comment state: success, no_ui_changes, or capture_failed
    def initialize(github_client:, repo:, pr_number:, commit_sha:, screenshots:,
      previous_screenshots: {}, artifact_name: nil, status: "success")
      @github_client = github_client
      @repo = repo
      @pr_number = pr_number
      @commit_sha = commit_sha
      @screenshots = screenshots
      @previous_screenshots = previous_screenshots
      @artifact_name = artifact_name
      @status = status
    end

    # Posts or updates the PR comment with screenshot images.
    #
    # @return [Sawyer::Resource] The created or updated comment
    def call
      body = build_comment_body
      existing = find_existing_comment

      if existing
        @github_client.update_comment(@repo, existing.id, body)
      else
        @github_client.add_comment(@repo, @pr_number, body)
      end
    end

    # Builds the markdown comment body without posting it.
    #
    # @return [String]
    def build_comment_body
      case @status
      when "no_ui_changes"
        return [
          MARKER,
          "## UI Screenshots",
          "",
          "This PR **no longer contains UI-facing changes** as of commit `#{short_sha}`.",
          "",
          "Any previously captured screenshots are outdated and can be ignored.",
          "",
          "---",
          "_Generated by Paid_",
          ""
        ].join("\n")
      when "capture_failed"
        return [
          MARKER,
          "## UI Screenshots",
          "",
          "This PR still includes **UI-facing changes**, but screenshot capture failed for commit `#{short_sha}`.",
          "",
          "Any previously captured screenshots are stale and should not be used for review.",
          "",
          "---",
          "_Generated by Paid_",
          ""
        ].join("\n")
      end

      if @screenshots.empty? && @artifact_name.present?
        return [
          MARKER,
          "## UI Screenshots",
          "",
          "This PR includes **UI-facing changes**, but inline screenshot upload is unavailable for commit `#{short_sha}`.",
          "",
          "Download the `#{@artifact_name}` workflow artifact from this run to review the captured PNG files.",
          "",
          "---",
          "_Generated by Paid_",
          ""
        ].join("\n")
      end

      if @screenshots.empty?
        return "#{MARKER}\n## UI Screenshots\n\nNo screenshots captured for commit `#{short_sha}`.\n"
      end

      grouped = group_by_category(@screenshots)

      annotated = @screenshots.any? { |s| s[:summary].present? }
      animated = @screenshots.any? { |s| s[:gif_url].present? }
      videos = @screenshots.select { |s| s[:video_url].present? }

      lines = [ MARKER ]
      lines << "## UI Screenshots"
      lines << ""
      lines << "This PR includes **UI-facing changes**. Screenshots captured from commit `#{short_sha}`."
      if animated
        lines << ""
        lines << "> Animated GIFs show the captured interaction flow. " \
                 "Static PNG fallbacks remain in the comparison columns."
      end
      if annotated
        lines << ""
        lines << "> Pages were scoped by Paid to those this change appears to affect; " \
                 "pages judged unrelated were skipped. Request a full capture if something looks missing."
      end
      lines << ""

      grouped.each do |category, category_screenshots|
        lines << "### #{category}"
        lines << ""

        if @previous_screenshots.any?
          header = annotated ? "| Page | What changed | Before | After |" : "| Page | Before | After |"
          divider = annotated ? "|------|--------------|--------|-------|" : "|------|--------|-------|"
          lines << header
          lines << divider

          category_screenshots.sort_by { |s| s[:route_name] }.each do |screenshot|
            lines << format_comparison_row(screenshot)
          end
        else
          header = annotated ? "| Page | What changed | Screenshot |" : "| Page | Screenshot |"
          divider = annotated ? "|------|--------------|-----------|" : "|------|-----------|"
          lines << header
          lines << divider

          category_screenshots.sort_by { |s| s[:route_name] }.each do |screenshot|
            lines << format_capture_row(screenshot, annotated: annotated)
          end
        end

        lines << ""
      end

      if videos.any?
        lines << "### Demo Videos"
        lines << ""
        videos.sort_by { |s| s[:route_name] }.each do |screenshot|
          filename = screenshot[:video_filename].presence || "#{screenshot[:route_name]}.webm"
          lines << "- [#{escape_markdown_label(filename)}](#{screenshot[:video_url]}) — #{route_label(screenshot[:route_name])}"
        end
        lines << ""
      end

      lines << "---"
      lines << "_Generated by Paid_"
      lines << ""

      lines.join("\n")
    end

    private

    def short_sha
      @commit_sha[0, 7]
    end

    def humanize_route(route_name)
      route_name.to_s.tr("_", " ").gsub(/\b\w/, &:upcase)
    end

    MAX_SUMMARY_LENGTH = 300

    # Renders the agent-derived "what changed" summary for a table cell. The text
    # is agent-influenced, so every markdown/HTML-significant character is
    # backslash-escaped (neutralizing images, links, raw HTML, and table
    # breakouts) and whitespace is collapsed to keep the row intact. GFM strips
    # the backslashes on render, so the displayed text stays clean.
    def changed_cell(screenshot)
      summary = screenshot[:summary].to_s.gsub(/\s+/, " ").strip
      return "—" if summary.empty?

      escape_markdown_text(summary.truncate(MAX_SUMMARY_LENGTH))
    end

    def format_comparison_row(screenshot)
      name = screenshot[:route_name]
      before_url = @previous_screenshots[name]

      before_cell = before_url ? markdown_image("before-#{name}", before_url) : "_New page_"
      after_cell = capture_cell(screenshot)
      cells = [ route_label(name) ]
      cells << changed_cell(screenshot) if annotated?
      cells += [ before_cell, after_cell ]
      "| #{cells.join(' | ')} |"
    end

    def format_capture_row(screenshot, annotated:)
      cells = [ route_label(screenshot[:route_name]) ]
      cells << changed_cell(screenshot) if annotated
      cells << capture_cell(screenshot)
      "| #{cells.join(' | ')} |"
    end

    def capture_cell(screenshot)
      name = screenshot[:route_name]
      if screenshot[:gif_url].present?
        markdown_image(name, screenshot[:gif_url])
      else
        markdown_image(name, screenshot[:url])
      end
    end

    def route_label(route_name)
      escape_markdown_label(humanize_route(route_name))
    end

    def markdown_image(alt_text, url)
      "![#{escape_markdown_label(alt_text)}](#{url})"
    end

    def escape_markdown_label(text)
      text.to_s.gsub(/[\\`\[\]()<>|]/) { |char| "\\#{char}" }
    end

    def escape_markdown_text(text)
      text.to_s.gsub(/[\\`*_{}\[\]()#+\-!<>|~]/) { |char| "\\#{char}" }
    end

    def annotated?
      @screenshots.any? { |s| s[:summary].present? }
    end

    def group_by_category(screenshots)
      grouped = screenshots.group_by { |s| category_for(s[:route_name]) }
      # Sort categories: unauthenticated first, then authenticated
      grouped.sort_by { |category, _| category == "Unauthenticated Pages" ? 0 : 1 }.to_h
    end

    def category_for(route_name)
      target = Screenshots::CaptureTargets::TARGETS[route_name.to_sym]
      if target&.requires_auth
        "Authenticated Pages"
      else
        "Unauthenticated Pages"
      end
    end

    def find_existing_comment
      comments = @github_client.recent_issue_comments(@repo, @pr_number)
      find_comment_with_marker(comments) || find_comment_in_older_pages(comments)
    end

    def find_comment_in_older_pages(comments)
      while comments.respond_to?(:next_older_page_url) && comments.next_older_page_url
        comments = @github_client.fetch_issue_comment_page(comments.next_older_page_url)
        existing = find_comment_with_marker(comments)
        return existing if existing
      end

      nil
    end

    def find_comment_with_marker(comments)
      comments.find { |comment| comment.body&.start_with?(MARKER) }
    end
  end
end
