# frozen_string_literal: true

module Screenshots
  # Builds and posts/updates a PR comment with inline screenshot images.
  #
  # Uses the `<!-- pr-screenshots-comment -->` marker for idempotent updates:
  # if a comment with that marker already exists, it is updated in place;
  # otherwise a new comment is created.
  #
  # @example
  #   Screenshots::PrComment.call(
  #     github_client: client,
  #     repo: "acme/web",
  #     pr_number: 42,
  #     commit_sha: "abc1234",
  #     screenshots: [
  #       { route_name: "dashboard", url: "https://signed-url..." },
  #       { route_name: "homepage",  url: "https://signed-url..." }
  #     ]
  #   )
  class PrComment
    MARKER = "<!-- pr-screenshots-comment -->"

    def self.call(...)
      new(...).call
    end

    # @param github_client [GithubClient] Authenticated GitHub API client
    # @param repo [String] Repository in "owner/name" format
    # @param pr_number [Integer] Pull request number
    # @param commit_sha [String] Commit SHA for the screenshots
    # @param screenshots [Array<Hash>] Each hash has :route_name and :url keys
    # @param previous_screenshots [Hash<String, String>] Mapping of route_name to
    #   signed URL from the previous commit's capture, used for before/after comparison
    # @param artifact_name [String, nil] Workflow artifact name when screenshots
    #   were captured but inline storage is unavailable
    # @param status [String] Comment state: success, no_ui_changes, or capture_failed
    def initialize(github_client:, repo:, pr_number:, commit_sha:, screenshots:,
      previous_screenshots: {}, artifact_name: nil, status: "success")
      @github_client = github_client
      @repo = repo
      @pr_number = pr_number
      @commit_sha = commit_sha
      @screenshots = screenshots
      @previous_screenshots = previous_screenshots
      @artifact_name = artifact_name
      @status = status
    end

    # Posts or updates the PR comment with screenshot images.
    #
    # @return [Sawyer::Resource] The created or updated comment
    def call
      body = build_comment_body
      existing = find_existing_comment

      if existing
        @github_client.update_comment(@repo, existing.id, body)
      else
        @github_client.add_comment(@repo, @pr_number, body)
      end
    end

    # Builds the markdown comment body without posting it.
    #
    # @return [String]
    def build_comment_body
      case @status
      when "no_ui_changes"
        return [
          MARKER,
          "## UI Screenshots",
          "",
          "This PR **no longer contains UI-facing changes** as of commit `#{short_sha}`.",
          "",
          "Any previously captured screenshots are outdated and can be ignored.",
          "",
          "---",
          "_Generated by Paid_",
          ""
        ].join("\n")
      when "capture_failed"
        return [
          MARKER,
          "## UI Screenshots",
          "",
          "This PR still includes **UI-facing changes**, but screenshot capture failed for commit `#{short_sha}`.",
          "",
          "Any previously captured screenshots are stale and should not be used for review.",
          "",
          "---",
          "_Generated by Paid_",
          ""
        ].join("\n")
      end

      if @screenshots.empty? && @artifact_name.present?
        return [
          MARKER,
          "## UI Screenshots",
          "",
          "This PR includes **UI-facing changes**, but inline screenshot upload is unavailable for commit `#{short_sha}`.",
          "",
          "Download the `#{@artifact_name}` workflow artifact from this run to review the captured PNG files.",
          "",
          "---",
          "_Generated by Paid_",
          ""
        ].join("\n")
      end

      if @screenshots.empty?
        return "#{MARKER}\n## UI Screenshots\n\nNo screenshots captured for commit `#{short_sha}`.\n"
      end

      lines = [ MARKER ]
      lines << "## UI Screenshots"
      lines << ""
      lines << "This PR includes **UI-facing changes**. Screenshots captured from commit `#{short_sha}`."
      lines << ""

      grouped = group_by_category(@screenshots)

      grouped.each do |category, category_screenshots|
        lines << "### #{category}"
        lines << ""

        if @previous_screenshots.any?
          lines << "| Page | Before | After |"
          lines << "|------|--------|-------|"

          category_screenshots.sort_by { |s| s[:route_name] }.each do |screenshot|
            name = screenshot[:route_name]
            after_url = screenshot[:url]
            before_url = @previous_screenshots[name]

            before_cell = before_url ? "![before-#{name}](#{before_url})" : "_New page_"
            lines << "| #{humanize_route(name)} | #{before_cell} | ![#{name}](#{after_url}) |"
          end
        else
          lines << "| Page | Screenshot |"
          lines << "|------|-----------|"

          category_screenshots.sort_by { |s| s[:route_name] }.each do |screenshot|
            name = screenshot[:route_name]
            url = screenshot[:url]
            lines << "| #{humanize_route(name)} | ![#{name}](#{url}) |"
          end
        end

        lines << ""
      end

      lines << "---"
      lines << "_Generated by Paid_"
      lines << ""

      lines.join("\n")
    end

    private

    def short_sha
      @commit_sha[0, 7]
    end

    def humanize_route(route_name)
      route_name.to_s.tr("_", " ").gsub(/\b\w/, &:upcase)
    end

    def group_by_category(screenshots)
      grouped = screenshots.group_by { |s| category_for(s[:route_name]) }
      # Sort categories: unauthenticated first, then authenticated
      grouped.sort_by { |category, _| category == "Unauthenticated Pages" ? 0 : 1 }.to_h
    end

    def category_for(route_name)
      target = Screenshots::CaptureTargets::TARGETS[route_name.to_sym]
      if target&.requires_auth
        "Authenticated Pages"
      else
        "Unauthenticated Pages"
      end
    end

    def find_existing_comment
      comments = @github_client.recent_issue_comments(@repo, @pr_number)
      find_comment_with_marker(comments) || find_comment_in_older_pages(comments)
    end

    def find_comment_in_older_pages(comments)
      while comments.respond_to?(:next_older_page_url) && comments.next_older_page_url
        comments = @github_client.fetch_issue_comment_page(comments.next_older_page_url)
        existing = find_comment_with_marker(comments)
        return existing if existing
      end

      nil
    end

    def find_comment_with_marker(comments)
      comments.find { |comment| comment.body&.start_with?(MARKER) }
    end
  end
end
