# frozen_string_literal: true

module Activities
  # Creates a single aggregated PR from the feature branch that contains
  # merged changes from multiple sub-task branches.
  #
  # The PR body includes a combined description referencing each sub-task
  # and its completion status.
  #
  # Input:
  #   project_id: ID of the project
  #   parent_issue_id: ID of the parent feature issue (optional)
  #   feature_branch: Name of the aggregated feature branch
  #   merged_branches: Array of branch names that were merged
  #   failed_merges: Array of { branch:, error: } for failed merges
  #   results: Array of child workflow results
  #
  # Returns:
  #   pull_request_url: URL of the created PR
  #   pull_request_number: Number of the created PR
  class CreateAggregatedPullRequestActivity < BaseActivity
    activity_name "CreateAggregatedPullRequest"

    def execute(input)
      project = Project.find(input[:project_id])
      parent_issue_id = input[:parent_issue_id]
      feature_branch = input[:feature_branch]
      merged_branches = input.fetch(:merged_branches, [])
      failed_merges = input.fetch(:failed_merges, [])
      results = input.fetch(:results, [])

      parent_issue = Issue.find_by(id: parent_issue_id) if parent_issue_id

      client = project.github_token.client
      pr = client.create_pull_request(
        project.full_name,
        base: project.default_branch,
        head: feature_branch,
        title: pr_title(parent_issue),
        body: pr_body(parent_issue, results, merged_branches, failed_merges),
        draft: true
      )

      add_pr_labels(client, project, pr.number)

      logger.info(
        message: "aggregated_pr.created",
        project_id: project.id,
        pull_request_url: pr.html_url,
        merged_branch_count: merged_branches.size,
        failed_merge_count: failed_merges.size
      )

      {
        pull_request_url: pr.html_url,
        pull_request_number: pr.number
      }
    end

    private

    def pr_title(parent_issue)
      if parent_issue
        "Feature ##{parent_issue.github_number}: #{parent_issue.title}".truncate(255)
      else
        "Aggregated feature changes"
      end
    end

    def pr_body(parent_issue, results, merged_branches, failed_merges)
      parts = []

      parts << "## Summary"
      parts << ""

      if parent_issue
        parts << "Aggregated pull request for feature ##{parent_issue.github_number}: **#{parent_issue.title}**"
      else
        parts << "Aggregated pull request combining changes from multiple sub-tasks."
      end

      parts << ""
      parts << "## Sub-task Results"
      parts << ""

      results.each do |result|
        issue = Issue.find_by(id: result[:issue_id]) if result[:issue_id]
        status = result[:success] ? "completed" : "failed"
        icon = result[:success] ? "\u2705" : "\u274c"

        if issue
          parts << "- #{icon} ##{issue.github_number}: #{issue.title} (#{status})"
        elsif result[:issue_id]
          parts << "- #{icon} Sub-task ##{result[:issue_id]} (#{status})"
        end
      end

      if failed_merges.any?
        parts << ""
        parts << "## Merge Conflicts"
        parts << ""
        parts << "The following branches could not be merged:"
        failed_merges.each do |failure|
          parts << "- `#{failure[:branch]}`: #{failure[:error]}"
        end
      end

      parts << ""
      parts << "---"
      parts << ""

      if parent_issue
        parts << "Closes ##{parent_issue.github_number}"
        parts << ""
      end

      parts << "_This pull request was automatically generated by [Paid](https://github.com/viamin/paid)._"

      parts.join("\n")
    end

    def add_pr_labels(client, project, pr_number)
      return unless project.auto_add_labels_enabled?

      client.add_labels_to_issue(project.full_name, pr_number, [
        project.generated_label_name,
        project.automation_label_name
      ])
    rescue GithubClient::Error => e
      logger.warn(
        message: "aggregated_pr.add_labels_failed",
        pr_number: pr_number,
        error: e.message
      )
    end
  end
end
