# frozen_string_literal: true

module Activities
  class CreatePullRequestActivity < BaseActivity
    activity_name "CreatePullRequest"

    def execute(agent_run_id:)
      agent_run = AgentRun.find(agent_run_id)
      project = agent_run.project
      issue = agent_run.issue

      client = project.github_token.client
      pr = client.create_pull_request(
        project.full_name,
        base: project.default_branch,
        head: agent_run.branch_name,
        title: pr_title(issue),
        body: pr_body(issue, agent_run)
      )

      agent_run.complete!(
        result_commit: agent_run.result_commit_sha,
        pr_url: pr.html_url,
        pr_number: pr.number
      )

      logger.info(
        message: "agent_execution.pull_request_created",
        agent_run_id: agent_run_id,
        pull_request_url: pr.html_url
      )

      { agent_run_id: agent_run_id, pull_request_url: pr.html_url, pull_request_number: pr.number }
    end

    private

    def pr_title(issue)
      return "Agent changes" unless issue

      "Fix ##{issue.github_number}: #{issue.title}".truncate(255)
    end

    def pr_body(issue, agent_run)
      parts = []
      parts << "Closes ##{issue.github_number}" if issue
      parts << ""
      parts << "Generated by Paid (agent: #{agent_run.agent_type})"
      parts.join("\n")
    end
  end
end
