# frozen_string_literal: true

module Activities
  # Creates an A/B test to compare evolved prompt variants against the
  # current control version. Integrates with the existing A/B testing
  # framework (AbTests::Create) and auto-starts the test.
  #
  # Skips creation when a running test already exists for the prompt
  # (only one running test is allowed per prompt).
  class CreateEvolutionAbTestActivity < BaseActivity
    activity_name "CreateEvolutionAbTest"

    def execute(input)
      prompt_id = input[:prompt_id]
      variant_version_ids = input[:variant_version_ids]
      min_samples = input.fetch(:min_samples_per_variant, 30)
      confidence = input.fetch(:confidence_threshold, 0.95)
      recovery_action_id = input[:recovery_action_id]

      prompt = Prompt.find(prompt_id)

      if prompt.ab_tests.running.exists?
        logger.info(
          message: "prompt_evolution.ab_test_already_running",
          prompt_id: prompt_id
        )
        existing = prompt.ab_tests.running.first
        track_recovery_action(recovery_action_id, existing, :already_running)
        return {
          ab_test_id: existing.id,
          status: :already_running,
          generation: evolution_generation(prompt)
        }
      end

      generation = evolution_generation(prompt)

      ab_test = AbTests::Create.call(
        prompt: prompt,
        name: "Evolution gen-#{generation} #{Date.current}",
        description: "Auto-generated by prompt evolution workflow (generation #{generation})",
        variant_version_ids: variant_version_ids,
        min_samples_per_variant: min_samples,
        confidence_threshold: confidence
      )

      ab_test.start!
      track_recovery_action(recovery_action_id, ab_test, :created)

      logger.info(
        message: "prompt_evolution.ab_test_created",
        prompt_id: prompt_id,
        ab_test_id: ab_test.id,
        variant_count: variant_version_ids.size,
        generation: generation
      )

      {
        ab_test_id: ab_test.id,
        status: :created,
        generation: generation
      }
    end

    private

    # Track evolution generation by counting completed evolution-originated
    # A/B tests for this prompt.
    def evolution_generation(prompt)
      prompt.ab_tests
        .where("name LIKE ?", "Evolution gen-%")
        .count + 1
    end

    def track_recovery_action(recovery_action_id, ab_test, status)
      return unless recovery_action_id

      action = QualityRecoveryAction.find_by(id: recovery_action_id)
      return unless action

      action.update!(
        result: {
          status: status,
          ab_test_id: ab_test.id,
          prompt_id: ab_test.prompt_id
        }
      )
    end
  end
end
