# frozen_string_literal: true

module Activities
  class CreatePullRequestActivity < BaseActivity
    activity_name "CreatePullRequest"

    PAID_GENERATED_LABEL = "paid-generated"

    def execute(input)
      agent_run_id = input[:agent_run_id]
      agent_run = AgentRun.find(agent_run_id)
      project = agent_run.project
      issue = agent_run.issue

      client = project.github_token.client
      pr = client.create_pull_request(
        project.full_name,
        base: project.default_branch,
        head: agent_run.branch_name,
        title: pr_title(issue),
        body: pr_body(issue, agent_run)
      )

      agent_run.complete!(
        result_commit: agent_run.result_commit_sha,
        pr_url: pr.html_url,
        pr_number: pr.number
      )

      add_pr_labels(client, project, pr.number, agent_run_id)

      agent_run.log!("system", "PR created: #{pr.html_url}")

      logger.info(
        message: "agent_execution.pull_request_created",
        agent_run_id: agent_run_id,
        pull_request_url: pr.html_url
      )

      { agent_run_id: agent_run_id, pull_request_url: pr.html_url, pull_request_number: pr.number }
    end

    private

    def pr_title(issue)
      return "Agent changes" unless issue

      "Fix ##{issue.github_number}: #{issue.title}".truncate(255)
    end

    def pr_body(issue, agent_run)
      parts = []

      agent_summary = agent_run.agent_run_logs.where(log_type: "stdout").order(:created_at).limit(500).pluck(:content).join("\n").strip
      if agent_summary.present?
        parts << agent_summary.truncate(50_000)
      else
        parts << "## Summary"
        parts << ""
        parts << "This pull request was automatically generated by [Paid](https://github.com/viamin/paid)."
      end

      parts << ""

      if issue
        parts << "---"
        parts << ""
        parts << "Closes ##{issue.github_number}"
      end

      parts.join("\n")
    end

    def add_pr_labels(client, project, pr_number, agent_run_id)
      client.add_labels_to_issue(project.full_name, pr_number, [ PAID_GENERATED_LABEL ])
    rescue GithubClient::Error => e
      logger.warn(
        message: "agent_execution.add_pr_labels_failed",
        agent_run_id: agent_run_id,
        pr_number: pr_number,
        error: e.message
      )
    end
  end
end
