# frozen_string_literal: true

module Activities
  class CreateStyleGuideAbTestActivity < BaseActivity
    activity_name "CreateStyleGuideAbTest"

    def execute(input)
      style_guide = StyleGuide.find(input[:style_guide_id])
      variant_version_ids = Array(input[:variant_version_ids])
      idempotency_key = Activities::IdempotencyKey.compute(style_guide.id, variant_version_ids)

      existing = style_guide.style_guide_ab_tests.find_by(idempotency_key: idempotency_key)
      if existing
        existing.start! if existing.draft?
        return { style_guide_ab_test_id: existing.id, status: existing.running? ? :already_running : :created }
      end

      ab_test = StyleGuideAbTests::Create.call(
        style_guide: style_guide,
        name: "Style guide evolution #{Date.current}",
        description: "Auto-generated by style guide evolution workflow",
        variant_version_ids: variant_version_ids,
        min_samples_per_variant: input.fetch(:min_samples_per_variant, 30),
        confidence_threshold: input.fetch(:confidence_threshold, 0.95),
        idempotency_key: idempotency_key
      )
      ab_test.start!

      { style_guide_ab_test_id: ab_test.id, status: :created }
    end
  end
end
