# frozen_string_literal: true

module Activities
  # Creates an A/B test to compare evolved prompt variants against the
  # current control version. Integrates with the existing A/B testing
  # framework (AbTests::Create) and auto-starts the test.
  #
  # Idempotent on Temporal retry (#2770): keyed on the prompt + exact variant
  # set, so a retry reuses the AbTest a previous attempt already created
  # (whether still draft or already running) instead of duplicating it.
  class CreateEvolutionAbTestActivity < BaseActivity
    activity_name "CreateEvolutionAbTest"

    def execute(input)
      prompt_id = input[:prompt_id]
      variant_version_ids = input[:variant_version_ids]
      min_samples = input.fetch(:min_samples_per_variant, 30)
      confidence = input.fetch(:confidence_threshold, 0.95)
      recovery_action_id = input[:recovery_action_id]
      idempotency_key = Activities::IdempotencyKey.compute(prompt_id, Array(variant_version_ids))

      prompt = Prompt.find(prompt_id)
      generation = evolution_generation(prompt)

      existing = prompt.ab_tests.find_by(idempotency_key: idempotency_key)
      if existing
        return reuse_existing_test(existing, recovery_action_id:)
      end

      if prompt.ab_tests.running.exists?
        logger.info(
          message: "prompt_evolution.ab_test_already_running",
          prompt_id: prompt_id
        )
        existing = prompt.ab_tests.running.first
        track_recovery_action(recovery_action_id, existing, :already_running)
        return {
          ab_test_id: existing.id,
          status: :already_running,
          generation: generation
        }
      end

      ab_test = AbTests::Create.call(
        prompt: prompt,
        name: "Evolution gen-#{generation} #{Date.current}",
        description: "Auto-generated by prompt evolution workflow (generation #{generation})",
        variant_version_ids: variant_version_ids,
        min_samples_per_variant: min_samples,
        confidence_threshold: confidence,
        idempotency_key: idempotency_key
      )

      ab_test.start!
      track_recovery_action(recovery_action_id, ab_test, :created)

      logger.info(
        message: "prompt_evolution.ab_test_created",
        prompt_id: prompt_id,
        ab_test_id: ab_test.id,
        variant_count: variant_version_ids.size,
        generation: generation
      )

      {
        ab_test_id: ab_test.id,
        status: :created,
        generation: generation
      }
    end

    private

    # A previous attempt of this activity already created the test for this
    # exact variant set. Reuse it: start a draft left behind by a crash that
    # happened after create but before start!, and surface the recovery action.
    def reuse_existing_test(existing, recovery_action_id:)
      existing.start! if existing.draft?

      status = existing.running? ? :already_running : :created
      track_recovery_action(recovery_action_id, existing, status)

      logger.info(
        message: "prompt_evolution.ab_test_reused_on_retry",
        prompt_id: existing.prompt_id,
        ab_test_id: existing.id,
        status: status
      )

      {
        ab_test_id: existing.id,
        status: status,
        generation: generation_from_test(existing)
      }
    end

    # Track evolution generation by counting completed evolution-originated
    # A/B tests for this prompt.
    def evolution_generation(prompt)
      prompt.ab_tests
        .where("name LIKE ?", "Evolution gen-%")
        .count + 1
    end

    # On a Temporal retry, the reused test was already created by a prior
    # attempt, so `evolution_generation` now counts it and would over-report
    # by one (returning N+1 for a gen-N test). That inflated value would leak
    # into the workflow result, which forwards this activity's `generation` as
    # its own. Parsing the generation out of the deterministic test name keeps
    # the retry invisible. Fall back to the recomputed count for any test not
    # named by this activity.
    def generation_from_test(test)
      parsed = test.name.to_s[/Evolution gen-(\d+)/, 1]
      parsed ? parsed.to_i : evolution_generation(test.prompt)
    end

    def track_recovery_action(recovery_action_id, ab_test, status)
      return unless recovery_action_id

      action = QualityRecoveryAction.find_by(id: recovery_action_id)
      return unless action

      action.update!(
        result: {
          status: status,
          ab_test_id: ab_test.id,
          prompt_id: ab_test.prompt_id
        }
      )
    end
  end
end
