# frozen_string_literal: true

module Activities
  class CreatePullRequestActivity < BaseActivity
    activity_name "CreatePullRequest"

    def execute(input)
      agent_run_id = input[:agent_run_id]
      agent_run = AgentRun.find(agent_run_id)
      track_phase(agent_run_id: agent_run_id, phase_key: "create_pull_request", phase_group: "post", agent_run: agent_run) do
        project = agent_run.project
        issue = agent_run.issue

        client = project.github_token.client
        pr = client.create_pull_request(
          project.full_name,
          base: project.default_branch,
          head: agent_run.branch_name,
          title: pr_title(issue),
          body: pr_body(issue, agent_run),
          draft: true
        )

        agent_run.complete!(
          result_commit: agent_run.result_commit_sha,
          pr_url: pr.html_url,
          pr_number: pr.number
        )

        add_pr_labels(client, project, pr.number, agent_run_id, issue: issue)

        agent_run.log!("system", "PR created: #{pr.html_url}")

        logger.info(
          message: "agent_execution.pull_request_created",
          agent_run_id: agent_run_id,
          pull_request_url: pr.html_url
        )

        { agent_run_id: agent_run_id, pull_request_url: pr.html_url, pull_request_number: pr.number }
      end
    end

    private

    def pr_title(issue)
      return "Agent changes" unless issue

      "Fix ##{issue.github_number}: #{issue.title}".truncate(255)
    end

    def pr_body(issue, agent_run)
      parts = []

      summary = agent_run.agent_summary
      description = generate_description(summary, issue, agent_run_id: agent_run.id)

      if description.present?
        parts << description
      elsif summary.present?
        parts << summary.truncate(50_000)
      else
        parts << "## Summary"
        parts << ""
        parts << "This pull request was automatically generated by [Paid](https://github.com/viamin/paid)."
      end

      parts << ""

      if issue
        parts << "---"
        parts << ""
        parts << "Closes ##{issue.github_number}"
      end

      parts.join("\n")
    end

    def generate_description(summary, issue, agent_run_id:)
      return nil if summary.blank?

      Llm::GeneratePrDescription.call(
        agent_summary: summary,
        issue_title: issue&.title,
        issue_body: issue&.body
      )
    rescue StandardError => e
      logger.warn(
        message: "agent_execution.pr_description_failed",
        agent_run_id: agent_run_id,
        issue_number: issue&.github_number,
        error_class: e.class.name,
        error: e.message
      )
      nil
    end

    def inherited_priority_labels(project, issue)
      return [] unless project.inherit_priority_labels?
      return [] if issue.blank? || issue.labels.blank?

      project.priority_label_names & Array(issue.labels)
    end

    def add_pr_labels(client, project, pr_number, agent_run_id, issue: nil)
      labels = []
      if project.auto_add_labels_enabled?
        labels << project.generated_label_name
        labels << project.automation_label_name
      end
      labels.concat(inherited_priority_labels(project, issue))
      labels.uniq!
      return if labels.empty?

      client.add_labels_to_issue(project.full_name, pr_number, labels)
    rescue GithubClient::Error => e
      logger.warn(
        message: "agent_execution.add_pr_labels_failed",
        agent_run_id: agent_run_id,
        pr_number: pr_number,
        error: e.message
      )
    end
  end
end
