# frozen_string_literal: true

module Activities
  class CreateGithubIssueActivity < BaseActivity
    activity_name "CreateGithubIssue"
    ISSUE_CREATION_ATTEMPT_PATTERN = /
      \A
      (?:bash|sh)\s+-lc\s+
      (?:
        ["']
      )?
      (?:
        [A-Za-z_][A-Za-z0-9_]*=
        (?:
          "[^"]*" |
          '[^']*' |
          [^\s"'\\]+
        )
        \s+
      )*
      \bcurl\b
      (?=.*?(?:-X\s+POST|--request\s+POST))
      (?=.*?\/repos\/[^\/\s]+\/[^\/\s]+\/issues(?:(?=[\s"'?\\])|\z))
      .*$
    /imx
    ISSUE_CREATION_FAILURE_PATTERNS = [
      /ActiveRecord::PendingMigrationError/,
      /Upstream request failed/i,
      /\b500\s+Internal\s+Server\s+Error\b/i,
      /\b502\s+Bad\s+Gateway\b/i
    ].freeze
    ISSUE_CREATION_FAILURE_LOG_BATCH_SIZE = 200
    ISSUE_CREATION_FAILURE_CONTEXT_LINES = 8

    def execute(input)
      agent_run_id = input[:agent_run_id]
      agent_run = AgentRun.find(agent_run_id)
      track_phase(agent_run_id: agent_run_id, phase_key: "create_github_issue", phase_group: "post", agent_run: agent_run) do
        project = agent_run.project

        client = project.github_token.client
        summary = agent_run.agent_summary_with_stderr_fallback
        validate_issue_creation_attempt!(agent_run)
        title = extract_title(summary, agent_run.custom_prompt)
        body = issue_body(summary)

        issue_labels = project.auto_add_labels_enabled? ? [ project.generated_label_name ] : []
        priority_label = priority_label_for(agent_run)
        issue_labels << priority_label if priority_label.present?

        gh_issue = client.create_issue(
          project.full_name,
          title: title,
          body: body,
          labels: issue_labels
        )

        sync_issue_record(project, gh_issue)

        agent_run.complete!(issue_url: gh_issue.html_url, issue_number: gh_issue.number)

        agent_run.log!("system", "Issue created: #{gh_issue.html_url}")

        logger.info(
          message: "agent_execution.github_issue_created",
          agent_run_id: agent_run_id,
          issue_url: gh_issue.html_url
        )

        ProcessRunQueueJob.perform_later

        { agent_run_id: agent_run_id, issue_url: gh_issue.html_url, issue_number: gh_issue.number }
      end
    end

    private

    def extract_title(summary, _custom_prompt = nil)
      # Try first markdown heading (any level) from agent output
      if summary.present?
        heading = summary[/^#+\s+(.+)$/, 1]&.sub(/\s*#+\s*$/, "")&.strip
        return heading.truncate(Llm::GenerateIssueTitle::MAX_TITLE_LENGTH) if heading.present?
      end

      # Fall back to LLM-generated title from agent output
      llm_title = Llm::GenerateIssueTitle.call(summary: summary)
      return llm_title if llm_title.present?

      # Last resort
      "Agent analysis"
    end

    def issue_body(summary)
      if summary.present?
        summary.truncate(50_000)
      else
        "This issue was automatically generated by [Paid](https://github.com/viamin/paid)."
      end
    end

    def priority_label_for(agent_run)
      return nil if agent_run.priority_tier.blank?

      agent_run.project.priority_label_for(agent_run.priority_tier)
    end

    def validate_issue_creation_attempt!(agent_run)
      return unless failed_issue_creation_attempt?(agent_run)

      agent_run.log!(
        "system",
        "Refused fallback issue creation because the agent already attempted and failed to create the GitHub issue"
      )

      raise Temporalio::Error::ApplicationError.new(
        "Agent already attempted and failed to create the GitHub issue; refusing fallback issue creation",
        type: "IssueDraftInvalid",
        non_retryable: true
      )
    end

    def failed_issue_creation_attempt?(agent_run)
      log_lines = []
      stream_states = Hash.new { |states, log_type| states[log_type] = { buffer: +"" } }

      agent_run.agent_run_logs
        .where(log_type: %w[stderr stdout])
        .select(:id, :log_type, :content)
        .find_in_batches(batch_size: ISSUE_CREATION_FAILURE_LOG_BATCH_SIZE) do |batch|
          batch.sort_by(&:id).each do |log|
            append_log_lines!(log_lines, stream_states[log.log_type], log)
          end
        end

      stream_states.each_value do |state|
        flush_log_line!(log_lines, state)
      end

      return false if log_lines.empty?

      failed_issue_creation_attempt_in_lines?(log_lines.sort_by { |entry| [ entry[:id], entry[:sequence] ] })
    end

    def issue_creation_attempt_line?(line)
      line.match?(ISSUE_CREATION_ATTEMPT_PATTERN)
    end

    def markdown_code_fence_line?(line)
      line.start_with?("```")
    end

    def append_log_lines!(log_lines, state, log)
      if state[:buffer].present? && !chunk_continues_previous_line?(state[:buffer], log.content)
        flush_log_line!(log_lines, state)
      end

      state[:line_id] ||= log.id
      state[:log_type] ||= log.log_type
      state[:buffer] << log.content
      state[:last_id] = log.id

      while (newline_index = state[:buffer].index("\n"))
        emit_log_line!(log_lines, state, state[:buffer].slice!(0, newline_index + 1).delete_suffix("\n"))
      end
    end

    def flush_log_line!(log_lines, state)
      return if state[:buffer].blank?

      emit_log_line!(log_lines, state, state[:buffer])
      state[:buffer] = +""
      state[:line_id] = nil
      state[:log_type] = nil
    end

    def emit_log_line!(log_lines, state, line)
      log_lines << {
        id: state[:line_id] || state[:last_id],
        sequence: log_lines.length,
        log_type: state[:log_type],
        line: line
      }
    end

    def chunk_continues_previous_line?(chunk, next_chunk)
      return false if chunk.end_with?("\n")

      line = chunk.lines.last.to_s
      next_line = next_chunk.lines.first.to_s
      stripped_line = line.strip
      return false if line.empty?

      stripped_line.match?(/\A`{1,2}\z/) ||
        incomplete_issue_creation_attempt_fragment?(stripped_line, next_line.strip)
    end

    def incomplete_issue_creation_attempt_fragment?(line, next_line = nil)
      return false unless line.match?(/\A(?:bash|sh)\s+-lc\s+(?:["'])?(?:(?:[A-Za-z_][A-Za-z0-9_]*=(?:"[^"]*"|'[^']*'|[^\s"'\\]+))\s+)*(?:\bcur(?:l\b?)?)?/im)

      combined_line = [ line, next_line.presence ].compact.join

      !issue_creation_attempt_line?(line) && issue_creation_attempt_line?(combined_line)
    end

    def failed_issue_creation_attempt_in_lines?(log_lines)
      inside_code_fence = Hash.new(false)

      log_lines.each_with_index.any? do |entry, index|
        stripped_line = entry[:line].strip
        log_type = entry[:log_type]

        if markdown_code_fence_line?(stripped_line)
          inside_code_fence[log_type] = !inside_code_fence[log_type]
          next false
        end

        next false if inside_code_fence[log_type]
        next false unless issue_creation_attempt_line?(stripped_line)

        failure_context = log_lines[index + 1, ISSUE_CREATION_FAILURE_CONTEXT_LINES].to_a.map { |line| line[:line] }.join("\n")
        next false if failure_context.blank?

        issue_creation_failure_marker?(failure_context)
      end
    end

    def issue_creation_failure_marker?(text)
      ISSUE_CREATION_FAILURE_PATTERNS.any? { |pattern| pattern.match?(text) }
    end

    def sync_issue_record(project, gh_issue)
      issue = project.issues.find_or_initialize_by(github_issue_id: gh_issue.id)
      issue.update!(
        github_number: gh_issue.number,
        title: gh_issue.title,
        body: gh_issue.body,
        github_creator_login: gh_issue.user&.login || "unknown",
        github_state: gh_issue.state,
        labels: (gh_issue.labels || []).map { |l| l.respond_to?(:name) ? l.name : l.to_s },
        is_pull_request: false,
        github_created_at: gh_issue.created_at,
        github_updated_at: gh_issue.updated_at
      )
    rescue => e
      logger.warn(
        message: "agent_execution.sync_created_issue_failed",
        project_id: project.id,
        issue_number: gh_issue.number,
        error: e.message
      )
    end
  end
end
