#!/usr/bin/env ruby
# frozen_string_literal: true

ENV["BUNDLE_GEMFILE"] ||= "/workspace/Gemfile"
ENV["BUNDLE_PATH"] ||= "/workspace/vendor/bundle"

require "bundler/setup"
require "pg"
require "uri"

args = ARGV.dup
file = nil
database = nil
output = nil

until args.empty?
  arg = args.shift

  case arg
  when "--file"
    file = args.shift
  when /\A--file=(.+)\z/
    file = ::Regexp.last_match(1)
  when "--output"
    output = args.shift
  when /\A--output=(.+)\z/
    output = ::Regexp.last_match(1)
  when "--set", "--quiet", "--no-psqlrc"
    args.shift if arg == "--set"
  when /\A-/
    next
  else
    database = arg
  end
end

abort "psql shim requires --file" if file.nil?
abort "psql shim requires database argument" if database.nil?

sql = File.read(file)

File.open(output, "w") { } if output && output != "/dev/null"

connection_target =
  if database.include?("://")
    database
  elsif ENV["DATABASE_URL"].to_s.include?("://")
    uri = URI.parse(ENV.fetch("DATABASE_URL"))
    uri.path = "/#{database}"
    uri.to_s
  else
    database
  end

connection = PG.connect(connection_target)
connection.exec(sql)
